import { NextRequest, NextResponse } from 'next/server'
import { readDataFile, writeDataFile } from '@/lib/data-utils'
import { Resend } from 'resend'

const RESEND_API_KEY = process.env.RESEND_API_KEY
const FROM_EMAIL = process.env.FROM_EMAIL || 'onboarding@resend.dev'
const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'

const resend = RESEND_API_KEY ? new Resend(RESEND_API_KEY) : null

type PromoCodeRecord = {
  code: string
  description?: string
  discountType: 'percentage' | 'fixed'
  discountValue: number
  minPurchase?: number
  maxDiscount?: number | null
  validFrom?: string
  validUntil?: string
  usageLimit?: number | null
  usedCount?: number
  active?: boolean
  isReferral?: boolean
  referrerEmail?: string | null
  friendUsesRemaining?: number | null
  referrerRewardAvailable?: boolean
  allowFirstTimeClient?: boolean
  autoGenerated?: boolean
  instructionsSentAt?: string | null
}

function generateReferralCode(): string {
  const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
  let value = ''
  for (let i = 0; i < 6; i += 1) {
    value += alphabet[Math.floor(Math.random() * alphabet.length)]
  }
  return `REF-${value}`
}

async function sendReferralEmail(referrerEmail: string, referrerName: string, code: string) {
  if (!resend) {
    console.warn('Resend not configured; skipping referral instruction email.')
    return
  }

  const safeName = referrerName || 'Beautiful'
  const html = `
    <div style="font-family: Arial, sans-serif; padding: 24px; color: #2F1A16; background-color: #FFF8FB;">
      <h2 style="margin-top: 0; color: #733D26;">🥰 LashDiary Referral - Share with a Friend 💋</h2>
      <p>Hi ${safeName},</p>
      <p>🥰 Thank you for being a loyal LashDiary client! Here's your personal referral code: 💋</p>
      <div style="margin: 16px 0; padding: 16px; background: #F3F0FF; border-radius: 12px; border: 2px dashed #7A6CFF; text-align: center;">
        <p style="margin: 0; font-size: 14px; color: #5143C5;">Share this code with a friend:</p>
        <p style="margin: 6px 0 0 0; font-size: 28px; font-weight: bold; letter-spacing: 2px;">${code}</p>
      </div>
      <ul style="padding-left: 18px; line-height: 1.6;">
        <li>Your friend gets <strong>10% off</strong> their first LashDiary visit when they use the code while booking.</li>
        <li>Once they book, <strong>you</strong> unlock <strong>10% off</strong> your next appointment using the <em>same code</em>.</li>
        <li>The code works for one friend at a time. After it's used, feel free to request a fresh referral code.</li>
      </ul>
      <p style="margin-top: 24px;">🥰 Ready to share the love? Simply forward this email or copy-and-paste your code into a message. 💋</p>
      <p>🌈 We appreciate you for helping the LashDiary family grow! 🥰</p>
      <p style="margin-top: 32px;">🤎 With love,<br/>The LashDiary Team 🥰</p>
      <p style="font-size: 12px; color: #7a7a7a; margin-top: 24px;">
        Book anytime at <a href="${BASE_URL}/booking" style="color: #7A6CFF; text-decoration: none;">${BASE_URL.replace(/^https?:\/\//, '')}</a>
      </p>
    </div>
  `

  await resend.emails.send({
    from: `LashDiary Referrals <${FROM_EMAIL}>`,
    to: referrerEmail,
    subject: 'Your Referral Code is Ready 🤎',
    html,
  })
}

async function sendFriendInviteEmail(friendEmail: string, code: string, referrerName: string) {
  if (!resend) {
    console.warn('Resend not configured; skipping friend referral invite email.')
    return
  }

  const safeName = referrerName || 'a LashDiary client'
  const html = `
    <div style="font-family: Arial, sans-serif; padding: 24px; color: #2F1A16; background-color: #FFF8FB;">
      <h2 style="margin-top: 0; color: #733D26;">🥰 ${safeName} sent you a LashDiary referral 💋</h2>
      <p>Hello!</p>
      <p>🥰 ${safeName} thought you'd love LashDiary. Use their personal referral code: 💋</p>
      <div style="margin: 16px 0; padding: 16px; background: #F3F0FF; border-radius: 12px; border: 2px dashed #7A6CFF; text-align: center;">
        <p style="margin: 0; font-size: 14px; color: #5143C5;">Referral code:</p>
        <p style="margin: 6px 0 0 0; font-size: 28px; font-weight: bold; letter-spacing: 2px;">${code}</p>
      </div>
      <p style="margin: 0 0 16px 0;">Use it when booking your first appointment to enjoy <strong>10% off</strong>.</p>
      <p style="margin: 0 0 16px 0;">Book now at <a href="${BASE_URL}/booking" style="color: #7A6CFF;">${BASE_URL.replace(/^https?:\/\//, '')}/booking</a>.</p>
      <p style="margin-top: 24px;">🥰 Can't wait to pamper you! 💋<br/>🤎 The LashDiary Team 🥰</p>
    </div>
  `

  await resend.emails.send({
    from: `LashDiary Referrals <${FROM_EMAIL}>`,
    to: friendEmail,
    subject: `You Received a Referral Code 🤎`,
    html,
  })
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const referrerEmail = (body?.referrerEmail || '').toString().trim().toLowerCase()
    const referrerName = (body?.referrerName || '').toString().trim()
    const friendEmailRaw = body?.friendEmail
    const friendEmail = typeof friendEmailRaw === 'string' ? friendEmailRaw.trim().toLowerCase() : null

    if (!referrerEmail || !referrerEmail.includes('@')) {
      return NextResponse.json({ error: 'A valid referrer email is required.' }, { status: 400 })
    }

    const promoData = await readDataFile<{ promoCodes: PromoCodeRecord[] }>('promo-codes.json', { promoCodes: [] })
    const promoCodes = Array.isArray(promoData.promoCodes) ? [...promoData.promoCodes] : []

    const existing = promoCodes.find(
      (promo) =>
        promo.isReferral === true &&
        (promo.referrerEmail || '').toLowerCase() === referrerEmail &&
        promo.active !== false &&
        ((typeof promo.friendUsesRemaining === 'number' && promo.friendUsesRemaining > 0) ||
          promo.referrerRewardAvailable === true),
    )

    if (existing) {
      if (
        existing.isReferral &&
        (existing.friendUsesRemaining ?? 0) <= 0 &&
        existing.referrerRewardAvailable === false
      ) {
        existing.friendUsesRemaining = 1
      }
      if (resend) {
        try {
          await sendReferralEmail(referrerEmail, referrerName, existing.code)
          existing.instructionsSentAt = new Date().toISOString()
          if (friendEmail) {
            await sendFriendInviteEmail(friendEmail, existing.code, referrerName)
          }
        } catch (emailError) {
          console.error('Failed to resend referral email:', emailError)
        }
      }
      await writeDataFile('promo-codes.json', { promoCodes })
      return NextResponse.json({ success: true, promoCode: existing, reused: true })
    }

    const newCode = generateReferralCode()
    const now = new Date()
    const oneYearLater = new Date(now)
    oneYearLater.setFullYear(oneYearLater.getFullYear() + 1)

    const referralPromo: PromoCodeRecord = {
      code: newCode,
      description: `Referral from ${referrerName || 'LashDiary client'}`,
      discountType: 'percentage',
      discountValue: 10,
      minPurchase: 0,
      maxDiscount: null,
      validFrom: now.toISOString().split('T')[0],
      validUntil: oneYearLater.toISOString().split('T')[0],
      usageLimit: null,
      usedCount: 0,
      active: true,
      isReferral: true,
      referrerEmail,
      friendUsesRemaining: 1,
      referrerRewardAvailable: false,
      allowFirstTimeClient: true,
      autoGenerated: true,
      instructionsSentAt: resend ? new Date().toISOString() : null,
    }

    promoCodes.push(referralPromo)
    await writeDataFile('promo-codes.json', { promoCodes })

    if (resend) {
      try {
        await sendReferralEmail(referrerEmail, referrerName, newCode)
        if (friendEmail) {
          await sendFriendInviteEmail(friendEmail, newCode, referrerName)
        }
      } catch (emailError) {
        console.error('Failed to send referral email:', emailError)
      }
    }

    return NextResponse.json({ success: true, promoCode: referralPromo, reused: false })
  } catch (error) {
    console.error('Error creating referral promo code:', error)
    return NextResponse.json({ error: 'Failed to create referral code' }, { status: 500 })
  }
}


