'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import Toast from '@/components/Toast'
import UnsavedChangesDialog from '@/components/UnsavedChangesDialog'

interface PromoCode {
  code: string
  description: string
  discountType: 'percentage' | 'fixed'
  discountValue: number
  minPurchase?: number
  maxDiscount?: number | null
  validFrom: string
  validUntil: string
  usageLimit?: number | null
  usedCount: number
  active: boolean
  isReferral?: boolean
  referrerEmail?: string | null
  friendUsesRemaining?: number | null
  referrerRewardAvailable?: boolean
  friendDiscountEnabled?: boolean
  friendDiscountPercent?: number | null
  referrerRewardPercent?: number | null
  friendReferralLimit?: number | null
  friendRedemptionCount?: number
  referrerRewardRedeemedCount?: number
  referralValidDays?: number | null
  referrerName?: string | null
  allowFirstTimeClient?: boolean
  autoGenerated?: boolean
  instructionsSentAt?: string | null
  isSalonReferral?: boolean
  salonName?: string | null
  salonEmail?: string | null
  salonPartnerType?: 'salon' | 'beautician' | 'influencer'
  clientDiscountPercent?: number | null
  salonCommissionPercent?: number | null
  salonUsageLimit?: number | null
  salonUsedCount?: number
  commissionTotal?: number
  commissionPaid?: number
}

const authorizedFetch = (input: RequestInfo | URL, init: RequestInit = {}) =>
  fetch(input, { credentials: 'include', ...init })

export default function AdminPromoCodes() {
  const [promoCodes, setPromoCodes] = useState<PromoCode[]>([])
  const [originalPromoCodes, setOriginalPromoCodes] = useState<PromoCode[]>([])
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null)
  const [showDialog, setShowDialog] = useState(false)
  const [pendingNavigation, setPendingNavigation] = useState<string | null>(null)
  const [referralDraft, setReferralDraft] = useState({
    referrerEmail: '',
    referrerName: '',
    friendEmail: '',
    friendDiscountEnabled: true,
    friendDiscountPercent: 10,
    referrerRewardPercent: 10,
    friendReferralLimit: 3,
    referralValidDays: 30,
    sendEmail: true,
  })
  const [creatingReferral, setCreatingReferral] = useState(false)
  const [sendingReferralEmailIndex, setSendingReferralEmailIndex] = useState<number | null>(null)
  const router = useRouter()
  const hasUnsavedChanges = JSON.stringify(promoCodes) !== JSON.stringify(originalPromoCodes)

  useEffect(() => {
    let isMounted = true

    const checkAuth = async () => {
      try {
        const response = await authorizedFetch('/api/admin/current-user')
        if (!response.ok) {
          throw new Error('Unauthorized')
        }
        const data = await response.json()
        if (!isMounted) return
        if (!data.authenticated) {
          router.replace('/admin/login')
          return
        }
        loadPromoCodes()
      } catch (error) {
        if (!isMounted) return
        router.replace('/admin/login')
      }
    }

    checkAuth()

    return () => {
      isMounted = false
    }
  }, [router])

  const loadPromoCodes = async () => {
    try {
      const response = await authorizedFetch('/api/admin/promo-codes')
      if (response.ok) {
        const data = await response.json()
        const normalized = (data.promoCodes || []).map((promo: PromoCode) => ({
          ...promo,
          isReferral: promo.isReferral ?? false,
          referrerEmail: promo.referrerEmail ?? '',
          friendUsesRemaining:
            typeof promo.friendUsesRemaining === 'number' ? promo.friendUsesRemaining : null,
          referrerRewardAvailable: promo.referrerRewardAvailable ?? false,
          friendDiscountEnabled: promo.friendDiscountEnabled !== false,
          friendDiscountPercent:
            promo.friendDiscountPercent !== null && promo.friendDiscountPercent !== undefined
              ? promo.friendDiscountPercent
              : promo.isReferral
                ? promo.discountValue ?? 10
                : null,
          referrerRewardPercent:
            promo.referrerRewardPercent !== null && promo.referrerRewardPercent !== undefined
              ? promo.referrerRewardPercent
              : promo.isReferral
                ? promo.discountValue ?? 10
                : null,
          friendReferralLimit:
            promo.friendReferralLimit !== null && promo.friendReferralLimit !== undefined
              ? promo.friendReferralLimit
              : promo.isReferral
                ? Math.max(1, (promo.friendUsesRemaining ?? 0) + (promo.friendRedemptionCount ?? 0))
                : null,
          friendRedemptionCount: promo.friendRedemptionCount ?? 0,
          referrerRewardRedeemedCount: promo.referrerRewardRedeemedCount ?? 0,
          referralValidDays: promo.referralValidDays ?? null,
          referrerName: promo.referrerName ?? '',
          allowFirstTimeClient:
            promo.allowFirstTimeClient ?? (promo.isReferral ? true : false),
          autoGenerated: promo.autoGenerated ?? false,
          instructionsSentAt: promo.instructionsSentAt ?? null,
          isSalonReferral: promo.isSalonReferral ?? false,
          salonName: promo.salonName ?? '',
          salonEmail: promo.salonEmail ?? '',
          clientDiscountPercent:
            promo.clientDiscountPercent !== null && promo.clientDiscountPercent !== undefined
              ? promo.clientDiscountPercent
              : promo.isSalonReferral
              ? 8
              : null,
          salonCommissionPercent:
            promo.salonCommissionPercent !== null && promo.salonCommissionPercent !== undefined
              ? promo.salonCommissionPercent
              : promo.isSalonReferral
              ? 4
              : null,
          salonUsageLimit:
            promo.salonUsageLimit !== null && promo.salonUsageLimit !== undefined
              ? promo.salonUsageLimit
              : promo.isSalonReferral
              ? 10
              : null,
          salonUsedCount: promo.salonUsedCount ?? 0,
          commissionTotal: promo.commissionTotal ?? 0,
          commissionPaid: promo.commissionPaid ?? 0,
        }))
        setPromoCodes(normalized)
        setOriginalPromoCodes(normalized)
      }
    } catch (error) {
      console.error('Error loading promo codes:', error)
    } finally {
      setLoading(false)
    }
  }

  // Handle unsaved changes warning
  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (hasUnsavedChanges) {
        e.preventDefault()
        e.returnValue = ''
        return ''
      }
    }

    window.addEventListener('beforeunload', handleBeforeUnload)

    return () => {
      window.removeEventListener('beforeunload', handleBeforeUnload)
    }
  }, [hasUnsavedChanges])

  // Intercept Link clicks
  const handleLinkClick = (e: React.MouseEvent<HTMLAnchorElement>, href: string) => {
    if (hasUnsavedChanges) {
      e.preventDefault()
      setPendingNavigation(href)
      setShowDialog(true)
    }
  }

  const handleDialogSave = async () => {
    await handleSave()
    if (pendingNavigation) {
      setShowDialog(false)
      router.push(pendingNavigation)
      setPendingNavigation(null)
    }
  }

  const handleDialogLeave = () => {
    setShowDialog(false)
    if (pendingNavigation) {
      router.push(pendingNavigation)
      setPendingNavigation(null)
    }
  }

  const handleDialogCancel = () => {
    setShowDialog(false)
    setPendingNavigation(null)
  }

  const handleSave = async () => {
    setSaving(true)
    setMessage(null)

    try {
      const response = await authorizedFetch('/api/admin/promo-codes', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ promoCodes }),
      })

      if (response.ok) {
        setMessage({ type: 'success', text: 'Promo codes updated successfully!' })
        setOriginalPromoCodes(promoCodes) // Update original to clear unsaved changes flag
        setShowDialog(false) // Close dialog if open
      } else {
        setMessage({ type: 'error', text: 'Failed to save promo codes' })
      }
    } catch (error) {
      setMessage({ type: 'error', text: 'An error occurred' })
    } finally {
      setSaving(false)
    }
  }

  const addPromoCode = () => {
    setPromoCodes([
      ...promoCodes,
      {
        code: '',
        description: '',
        discountType: 'percentage',
        discountValue: 10,
        minPurchase: 0,
        maxDiscount: null,
        validFrom: new Date().toISOString().split('T')[0],
        validUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        usageLimit: null,
        usedCount: 0,
        active: true,
        isReferral: false,
        referrerEmail: '',
        friendUsesRemaining: 1,
        referrerRewardAvailable: false,
        allowFirstTimeClient: true,
        autoGenerated: false,
        friendReferralLimit: 3,
        friendRedemptionCount: 0,
        referrerRewardRedeemedCount: 0,
        referralValidDays: 30,
        instructionsSentAt: null,
        isSalonReferral: false,
        salonName: '',
        salonEmail: '',
        salonPartnerType: 'salon',
        clientDiscountPercent: 8,
        salonCommissionPercent: 4,
        salonUsageLimit: 10,
        salonUsedCount: 0,
        commissionTotal: 0,
        commissionPaid: 0,
      },
    ])
  }

  const updatePromoCode = (index: number, field: keyof PromoCode, value: any) => {
    setPromoCodes((prev) => {
      const updated = [...prev]
      const current = { ...updated[index] }

      const ensureNumber = (input: any, fallback: number | null = null) => {
        if (input === '' || input === null || input === undefined) return fallback
        const parsed = Number(input)
        return Number.isFinite(parsed) ? parsed : fallback
      }

      if (field === 'isReferral') {
        const enabled = Boolean(value)
        current.isReferral = enabled
        if (enabled) {
          current.isSalonReferral = false
          current.salonPartnerType = undefined
        }
        current.allowFirstTimeClient = enabled ? true : current.allowFirstTimeClient ?? false
        current.discountType = 'percentage'
        if (enabled) {
          current.friendDiscountEnabled = current.friendDiscountEnabled !== false
          current.friendDiscountPercent =
            typeof current.friendDiscountPercent === 'number'
              ? current.friendDiscountPercent
              : current.discountValue ?? 10
          current.referrerRewardPercent =
            typeof current.referrerRewardPercent === 'number'
              ? current.referrerRewardPercent
              : current.discountValue ?? 10
          current.friendReferralLimit =
            typeof current.friendReferralLimit === 'number' ? current.friendReferralLimit : 3
          current.friendRedemptionCount = current.friendRedemptionCount ?? 0
          current.referrerRewardRedeemedCount = current.referrerRewardRedeemedCount ?? 0
          current.referralValidDays =
            typeof current.referralValidDays === 'number' ? current.referralValidDays : 30
          if (!current.discountValue || current.discountValue < 0) {
            current.discountValue = current.friendDiscountPercent ?? 10
          }
        }
        if (enabled && (current.friendUsesRemaining === null || current.friendUsesRemaining === undefined)) {
          current.friendUsesRemaining = 1
        }
      } else if (field === 'friendDiscountEnabled') {
        current.friendDiscountEnabled = Boolean(value)
      } else if (field === 'friendDiscountPercent') {
        const amount = ensureNumber(value, 0) ?? 0
        current.friendDiscountPercent = amount
        current.discountValue = amount
      } else if (field === 'referrerRewardPercent') {
        current.referrerRewardPercent = ensureNumber(value, 0) ?? 0
      } else if (field === 'friendReferralLimit') {
        const amount = ensureNumber(value, 3) ?? 3
        current.friendReferralLimit = Math.max(1, Math.min(10, Math.round(amount)))
        current.friendUsesRemaining = Math.max(
          0,
          current.friendReferralLimit - (current.friendRedemptionCount ?? 0),
        )
      } else if (field === 'referralValidDays') {
        const amount = ensureNumber(value, 30) ?? 30
        current.referralValidDays = Math.max(1, Math.min(365, Math.round(amount)))
        const validUntil = new Date()
        validUntil.setDate(validUntil.getDate() + current.referralValidDays)
        current.validUntil = validUntil.toISOString().split('T')[0]
      } else if (field === 'isSalonReferral') {
        const enabled = Boolean(value)
        current.isSalonReferral = enabled
        if (enabled) {
          current.isReferral = false
          current.discountType = 'percentage'
          const clientDiscount = ensureNumber(current.clientDiscountPercent, 8) ?? 8
          current.clientDiscountPercent = clientDiscount
          current.discountValue = clientDiscount
          current.salonCommissionPercent = ensureNumber(current.salonCommissionPercent, 4) ?? 4
          const usageLimit = ensureNumber(current.salonUsageLimit, 10)
          current.salonUsageLimit = usageLimit === null ? 10 : usageLimit
          if (!current.usageLimit || current.usageLimit < (current.salonUsageLimit ?? 0)) {
            current.usageLimit = current.salonUsageLimit ?? current.usageLimit
          }
          current.salonName = current.salonName ?? ''
          current.salonEmail = current.salonEmail ?? ''
          current.salonPartnerType = current.salonPartnerType || 'salon'
        } else {
          current.salonPartnerType = undefined
        }
      } else if (field === 'discountValue') {
        const amount = ensureNumber(value, 0) ?? 0
        current.discountValue = amount
        if (current.isSalonReferral) {
          current.clientDiscountPercent = amount
        }
      } else if (field === 'clientDiscountPercent') {
        const amount = ensureNumber(value, null)
        current.clientDiscountPercent = amount
        if (current.isSalonReferral && amount !== null) {
          current.discountType = 'percentage'
          current.discountValue = amount
        }
      } else if (field === 'salonCommissionPercent') {
        current.salonCommissionPercent = ensureNumber(value, null)
      } else if (field === 'salonPartnerType') {
        const allowed = ['salon', 'beautician', 'influencer']
        current.salonPartnerType = allowed.includes(value) ? (value as 'salon' | 'beautician' | 'influencer') : 'salon'
      } else if (field === 'salonUsageLimit') {
        current.salonUsageLimit = ensureNumber(value, null)
        if (current.isSalonReferral && current.salonUsageLimit && (!current.usageLimit || current.usageLimit < current.salonUsageLimit)) {
          current.usageLimit = current.salonUsageLimit
        }
      } else if (field === 'usageLimit') {
        current.usageLimit = ensureNumber(value, null)
      } else if (field === 'minPurchase' || field === 'maxDiscount') {
        (current as any)[field] = ensureNumber(value, field === 'minPurchase' ? 0 : null)
      } else {
        ;(current as any)[field] = value
      }

      updated[index] = current
      return updated
    })
  }

  const removePromoCode = (index: number) => {
    setPromoCodes((prev) => prev.filter((_, i) => i !== index))
  }

  const handleCreateClientReferral = async () => {
    const email = referralDraft.referrerEmail.trim().toLowerCase()
    if (!email || !email.includes('@')) {
      setMessage({ type: 'error', text: 'Enter a valid referrer email.' })
      return
    }

    setCreatingReferral(true)
    setMessage(null)

    try {
      const response = await authorizedFetch('/api/admin/promo-codes/create-client-referral', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          referrerEmail: email,
          referrerName: referralDraft.referrerName.trim(),
          friendEmail: referralDraft.friendEmail.trim() || null,
          friendDiscountEnabled: referralDraft.friendDiscountEnabled,
          friendDiscountPercent: referralDraft.friendDiscountPercent,
          referrerRewardPercent: referralDraft.referrerRewardPercent,
          friendReferralLimit: referralDraft.friendReferralLimit,
          referralValidDays: referralDraft.referralValidDays,
          sendEmail: referralDraft.sendEmail,
        }),
      })

      const data = await response.json()
      if (!response.ok) {
        setMessage({ type: 'error', text: data.error || 'Failed to create referral code.' })
        return
      }

      await loadPromoCodes()
      setMessage({
        type: 'success',
        text: data.reused
          ? `Referral code ${data.promoCode.code} updated${data.emailSent ? ' and emailed' : ''}.`
          : `Referral code ${data.promoCode.code} created${data.emailSent ? ' and emailed' : ''}.`,
      })
      setReferralDraft((prev) => ({ ...prev, referrerEmail: '', referrerName: '', friendEmail: '' }))
    } catch {
      setMessage({ type: 'error', text: 'Failed to create referral code.' })
    } finally {
      setCreatingReferral(false)
    }
  }

  const handleSendReferralEmail = async (index: number) => {
    const promo = promoCodes[index]
    if (!promo?.code?.trim()) {
      setMessage({ type: 'error', text: 'Save a promo code first.' })
      return
    }

    setSendingReferralEmailIndex(index)
    setMessage(null)

    try {
      const response = await authorizedFetch('/api/admin/promo-codes/send-referral-email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code: promo.code.trim() }),
      })
      const data = await response.json()
      if (!response.ok) {
        setMessage({ type: 'error', text: data.error || 'Failed to send email.' })
        return
      }

      setPromoCodes((prev) => {
        const updated = [...prev]
        updated[index] = {
          ...updated[index],
          instructionsSentAt: data.instructionsSentAt || new Date().toISOString(),
        }
        return updated
      })
      setOriginalPromoCodes((prev) => {
        const updated = [...prev]
        if (updated[index]) {
          updated[index] = {
            ...updated[index],
            instructionsSentAt: data.instructionsSentAt || new Date().toISOString(),
          }
        }
        return updated
      })
      setMessage({ type: 'success', text: `Referral instructions sent for ${promo.code}.` })
    } catch {
      setMessage({ type: 'error', text: 'Failed to send referral email.' })
    } finally {
      setSendingReferralEmailIndex(null)
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-baby-pink-light flex items-center justify-center">
        <div className="text-brown">Loading...</div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-baby-pink-light py-8 px-4">
      <div className="max-w-6xl mx-auto">
        <div className="mb-6 flex justify-between items-center">
          {hasUnsavedChanges && (
            <div className="text-sm text-orange-600 font-medium">
              ⚠️ You have unsaved changes
            </div>
          )}
          <Link 
            href="/admin/dashboard" 
            className="text-brown hover:text-brown-dark"
            onClick={(e) => handleLinkClick(e, '/admin/dashboard')}
          >
            ← Back to Dashboard
          </Link>
          <div className="flex gap-4">
            <button
              onClick={addPromoCode}
              className="bg-brown-dark text-white px-6 py-2 rounded-lg hover:bg-brown transition-colors"
            >
              + Add Promo Code
            </button>
            <button
              onClick={handleSave}
              disabled={saving}
              className="bg-brown-dark text-white px-6 py-2 rounded-lg hover:bg-brown transition-colors disabled:opacity-50"
            >
              {saving ? 'Saving...' : 'Save Changes'}
            </button>
          </div>
        </div>

        {/* Toast Notification */}
        {message && (
          <Toast
            message={message.text}
            type={message.type}
            onClose={() => setMessage(null)}
          />
        )}

        <div className="bg-white rounded-lg shadow-lg p-8">
          <h1 className="text-4xl font-display text-brown-dark mb-4">Promo Codes Management</h1>
          <p className="text-sm text-brown mb-6">
            Default friend/reward percentages come from{' '}
            <Link href="/admin/policies" className="text-brown-dark underline">
              Policies
            </Link>{' '}
            (referral variables). Override them per code below.
          </p>

          <div className="mb-8 rounded-lg border border-brown-light/50 bg-pink-light/40 p-6 space-y-4">
            <h2 className="text-xl font-display text-brown-dark">Quick create: client referral</h2>
            <p className="text-sm text-brown">
              Generate a personal code for an existing client. Their friend can book with an optional discount; once
              the friend completes a booking, the client unlocks their reward using the same code.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-brown-dark mb-1">Client email *</label>
                <input
                  type="email"
                  value={referralDraft.referrerEmail}
                  onChange={(e) => setReferralDraft((p) => ({ ...p, referrerEmail: e.target.value }))}
                  placeholder="client@example.com"
                  className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-brown-dark mb-1">Client name</label>
                <input
                  type="text"
                  value={referralDraft.referrerName}
                  onChange={(e) => setReferralDraft((p) => ({ ...p, referrerName: e.target.value }))}
                  placeholder="Jane"
                  className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-brown-dark mb-1">Friend discount (%)</label>
                <input
                  type="number"
                  min={0}
                  max={100}
                  disabled={!referralDraft.friendDiscountEnabled}
                  value={referralDraft.friendDiscountPercent}
                  onChange={(e) =>
                    setReferralDraft((p) => ({
                      ...p,
                      friendDiscountPercent: Math.max(0, Math.min(100, parseInt(e.target.value, 10) || 0)),
                    }))
                  }
                  className="w-full px-3 py-2 border border-brown-light rounded bg-white disabled:opacity-50"
                />
                <label className="flex items-center gap-2 text-xs text-brown mt-2">
                  <input
                    type="checkbox"
                    checked={referralDraft.friendDiscountEnabled}
                    onChange={(e) =>
                      setReferralDraft((p) => ({ ...p, friendDiscountEnabled: e.target.checked }))
                    }
                  />
                  Give friend a discount (uncheck for referral tracking only)
                </label>
              </div>
              <div>
                <label className="block text-sm font-medium text-brown-dark mb-1">Client reward (%)</label>
                <input
                  type="number"
                  min={0}
                  max={100}
                  value={referralDraft.referrerRewardPercent}
                  onChange={(e) =>
                    setReferralDraft((p) => ({
                      ...p,
                      referrerRewardPercent: Math.max(0, Math.min(100, parseInt(e.target.value, 10) || 0)),
                    }))
                  }
                  className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-brown-dark mb-1">Max friends who can use code</label>
                <input
                  type="number"
                  min={1}
                  max={10}
                  value={referralDraft.friendReferralLimit}
                  onChange={(e) =>
                    setReferralDraft((p) => ({
                      ...p,
                      friendReferralLimit: Math.max(1, Math.min(10, parseInt(e.target.value, 10) || 3)),
                    }))
                  }
                  className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                />
                <p className="text-xs text-brown mt-1">Example: 3 friends means the client can earn up to 3 rewards.</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-brown-dark mb-1">Friend code valid for (days)</label>
                <input
                  type="number"
                  min={1}
                  max={365}
                  value={referralDraft.referralValidDays}
                  onChange={(e) =>
                    setReferralDraft((p) => ({
                      ...p,
                      referralValidDays: Math.max(1, Math.min(365, parseInt(e.target.value, 10) || 30)),
                    }))
                  }
                  className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                />
                <p className="text-xs text-brown mt-1">Friends must use the code within this window.</p>
              </div>
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-brown-dark mb-1">
                  Friend email (optional — sends them the code directly)
                </label>
                <input
                  type="email"
                  value={referralDraft.friendEmail}
                  onChange={(e) => setReferralDraft((p) => ({ ...p, friendEmail: e.target.value }))}
                  placeholder="friend@example.com"
                  className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                />
              </div>
            </div>
            <div className="flex flex-wrap items-center gap-4">
              <label className="flex items-center gap-2 text-sm text-brown-dark">
                <input
                  type="checkbox"
                  checked={referralDraft.sendEmail}
                  onChange={(e) => setReferralDraft((p) => ({ ...p, sendEmail: e.target.checked }))}
                />
                Email instructions to client
              </label>
              <button
                type="button"
                onClick={handleCreateClientReferral}
                disabled={creatingReferral}
                className="bg-brown-dark text-white px-5 py-2 rounded-lg hover:bg-brown transition-colors disabled:opacity-50"
              >
                {creatingReferral ? 'Creating…' : 'Create & send referral code'}
              </button>
            </div>
          </div>

          <div className="space-y-6">
            {promoCodes.map((promo, index) => (
              <div key={index} className="bg-pink-light rounded-lg p-6 space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Code *</label>
                    <input
                      type="text"
                      value={promo.code}
                      onChange={(e) => updatePromoCode(index, 'code', e.target.value.toUpperCase())}
                      placeholder="REFER10"
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Description</label>
                    <input
                      type="text"
                      value={promo.description}
                      onChange={(e) => updatePromoCode(index, 'description', e.target.value)}
                      placeholder="10% off for referrals"
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Discount Type</label>
                    <select
                      value={promo.discountType}
                      onChange={(e) => updatePromoCode(index, 'discountType', e.target.value)}
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    >
                      <option value="percentage">Percentage</option>
                      <option value="fixed">Fixed Amount (KSH)</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Discount Value *</label>
                    <input
                      type="number"
                      value={promo.discountValue}
                      onChange={(e) => updatePromoCode(index, 'discountValue', parseFloat(e.target.value) || 0)}
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Min Purchase (KSH)</label>
                    <input
                      type="number"
                      value={promo.minPurchase || 0}
                      onChange={(e) => updatePromoCode(index, 'minPurchase', parseFloat(e.target.value) || 0)}
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Max Discount (KSH, leave empty for no limit)</label>
                    <input
                      type="number"
                      value={promo.maxDiscount || ''}
                      onChange={(e) => updatePromoCode(index, 'maxDiscount', e.target.value ? parseFloat(e.target.value) : null)}
                      placeholder="No limit"
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Valid From *</label>
                    <input
                      type="date"
                      value={promo.validFrom}
                      onChange={(e) => updatePromoCode(index, 'validFrom', e.target.value)}
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Valid Until *</label>
                    <input
                      type="date"
                      value={promo.validUntil}
                      onChange={(e) => updatePromoCode(index, 'validUntil', e.target.value)}
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Usage Limit (leave empty for unlimited)</label>
                    <input
                      type="number"
                      value={promo.usageLimit || ''}
                      onChange={(e) => updatePromoCode(index, 'usageLimit', e.target.value ? parseInt(e.target.value) : null)}
                      placeholder="Unlimited"
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div className="flex items-end gap-4">
                    <label className="flex items-center">
                      <input
                        type="checkbox"
                        checked={promo.active}
                        onChange={(e) => updatePromoCode(index, 'active', e.target.checked)}
                        className="mr-2"
                      />
                      <span className="text-sm font-medium text-brown-dark">Active</span>
                    </label>
                    <div className="text-sm text-brown">
                      Used: {promo.usedCount} {promo.usageLimit ? `/ ${promo.usageLimit}` : ''}
                    </div>
                  </div>
                </div>
                <div className="md:col-span-2 border-t border-brown-light/40 pt-4 mt-2 space-y-6">
                  <div>
                    <div className="flex items-center gap-2 text-sm font-semibold text-brown-dark">
                      <label className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={promo.isReferral || false}
                          onChange={(e) => updatePromoCode(index, 'isReferral', e.target.checked)}
                        />
                        Client referral (friend-to-friend)
                      </label>
                    </div>
                    <p className="text-xs text-brown mt-1">
                      Friend and referrer rewards can differ. Set 0% friend discount if you only want to reward the
                      referring client after their friend books.
                    </p>
                    {(promo.isReferral || false) && (
                      <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Referrer name</label>
                          <input
                            type="text"
                            value={promo.referrerName || ''}
                            onChange={(e) => updatePromoCode(index, 'referrerName', e.target.value)}
                            placeholder="Client name for emails"
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">
                            Referrer Email *
                          </label>
                          <input
                            type="email"
                            value={promo.referrerEmail || ''}
                            onChange={(e) => updatePromoCode(index, 'referrerEmail', e.target.value)}
                            placeholder="client@example.com"
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">
                            Max friends who can use this code
                          </label>
                          <input
                            type="number"
                            min={1}
                            max={10}
                            value={promo.friendReferralLimit ?? 3}
                            onChange={(e) =>
                              updatePromoCode(
                                index,
                                'friendReferralLimit',
                                e.target.value === '' ? 3 : Math.max(1, parseInt(e.target.value) || 3),
                              )
                            }
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                          <p className="text-xs text-brown mt-1">
                            Completed: {promo.friendRedemptionCount ?? 0} / {promo.friendReferralLimit ?? 3}. Remaining:{' '}
                            {Math.max(0, (promo.friendReferralLimit ?? 3) - (promo.friendRedemptionCount ?? 0))}.
                          </p>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">
                            Friend code valid for (days)
                          </label>
                          <input
                            type="number"
                            min={1}
                            max={365}
                            value={promo.referralValidDays ?? ''}
                            onChange={(e) =>
                              updatePromoCode(
                                index,
                                'referralValidDays',
                                e.target.value === '' ? 30 : Math.max(1, parseInt(e.target.value) || 30),
                              )
                            }
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                          <p className="text-xs text-brown mt-1">Friends must redeem before the Valid Until date.</p>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Friend discount (%)</label>
                          <input
                            type="number"
                            min={0}
                            max={100}
                            disabled={promo.friendDiscountEnabled === false}
                            value={promo.friendDiscountPercent ?? promo.discountValue ?? 0}
                            onChange={(e) =>
                              updatePromoCode(index, 'friendDiscountPercent', parseFloat(e.target.value) || 0)
                            }
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white disabled:opacity-50"
                          />
                          <label className="flex items-center gap-2 text-xs text-brown mt-2">
                            <input
                              type="checkbox"
                              checked={promo.friendDiscountEnabled !== false}
                              onChange={(e) => updatePromoCode(index, 'friendDiscountEnabled', e.target.checked)}
                            />
                            Friend gets a discount
                          </label>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">
                            Referrer reward (%)
                          </label>
                          <input
                            type="number"
                            min={0}
                            max={100}
                            value={promo.referrerRewardPercent ?? promo.discountValue ?? 10}
                            onChange={(e) =>
                              updatePromoCode(index, 'referrerRewardPercent', parseFloat(e.target.value) || 0)
                            }
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                          <p className="text-xs text-brown mt-1">
                            Each successful friend adds this reward. Current available reward:{' '}
                            {Math.min(
                              100,
                              Math.max(
                                0,
                                ((promo.friendRedemptionCount ?? 0) - (promo.referrerRewardRedeemedCount ?? 0)) *
                                  (promo.referrerRewardPercent ?? promo.discountValue ?? 0),
                              ),
                            )}
                            %.
                          </p>
                        </div>
                        <div>
                          <label className="flex items-center gap-2 text-sm font-medium text-brown-dark mb-1">
                            <input
                              type="checkbox"
                              checked={promo.referrerRewardAvailable || false}
                              onChange={(e) => updatePromoCode(index, 'referrerRewardAvailable', e.target.checked)}
                            />
                            Referrer reward still available
                          </label>
                          <p className="text-xs text-brown mt-1">
                            This is updated automatically when friends redeem the code and when the client uses their
                            accumulated reward.
                          </p>
                        </div>
                        <div>
                          <label className="flex items-center gap-2 text-sm font-medium text-brown-dark mb-1">
                            <input
                              type="checkbox"
                              checked={promo.allowFirstTimeClient ?? true}
                              onChange={(e) => updatePromoCode(index, 'allowFirstTimeClient', e.target.checked)}
                            />
                            Allow first-time clients to use
                          </label>
                          <p className="text-xs text-brown mt-1">
                            Enable so new clients can redeem referral codes even on their first visit.
                          </p>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">
                            Instructions last sent
                          </label>
                          <input
                            type="text"
                            value={promo.instructionsSentAt ? new Date(promo.instructionsSentAt).toLocaleString() : 'Never'}
                            readOnly
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white text-sm text-brown-dark/70"
                          />
                        </div>
                        <div className="md:col-span-2">
                          <button
                            type="button"
                            onClick={() => handleSendReferralEmail(index)}
                            disabled={sendingReferralEmailIndex === index || !promo.referrerEmail}
                            className="bg-brown-dark text-white px-4 py-2 rounded-lg hover:bg-brown transition-colors disabled:opacity-50 text-sm"
                          >
                            {sendingReferralEmailIndex === index
                              ? 'Sending…'
                              : 'Email referral instructions to client'}
                          </button>
                        </div>
                      </div>
                    )}
                  </div>

                  <div className="border-t border-brown-light/40 pt-4">
                    <div className="flex items-center gap-2 text-sm font-semibold text-brown-dark">
                      <label className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={promo.isSalonReferral || false}
                          onChange={(e) => updatePromoCode(index, 'isSalonReferral', e.target.checked)}
                        />
                        Partner referral cards (salon / beautician / influencer)
                      </label>
                    </div>
                    <p className="text-xs text-brown mt-1">
                      Issue up to 10 cards per partner. New clients get a discount and your partner earns commission once the booking is confirmed.
                    </p>
                    {(promo.isSalonReferral || false) && (
                      <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Partner Type *</label>
                          <select
                            value={promo.salonPartnerType || 'salon'}
                            onChange={(e) =>
                              updatePromoCode(
                                index,
                                'salonPartnerType',
                                (['salon', 'beautician', 'influencer'].includes(e.target.value)
                                  ? e.target.value
                                  : 'salon') as 'salon' | 'beautician' | 'influencer',
                              )
                            }
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          >
                            <option value="salon">Salon</option>
                            <option value="beautician">Beautician</option>
                            <option value="influencer">Influencer / Creator</option>
                          </select>
                          <p className="text-xs text-brown mt-1">
                            Used for onboarding emails and partner reporting.
                          </p>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Partner Name *</label>
                          <input
                            type="text"
                            value={promo.salonName || ''}
                            onChange={(e) => updatePromoCode(index, 'salonName', e.target.value)}
                            placeholder="Glow Beauty Studio"
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Partner Contact Email *</label>
                          <input
                            type="email"
                            value={promo.salonEmail || ''}
                            onChange={(e) => updatePromoCode(index, 'salonEmail', e.target.value)}
                            placeholder="beautician@example.com"
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Client Discount (%) *</label>
                          <input
                            type="number"
                            min={0}
                            value={promo.clientDiscountPercent ?? ''}
                            onChange={(e) =>
                              updatePromoCode(
                                index,
                                'clientDiscountPercent',
                                e.target.value === '' ? null : parseFloat(e.target.value) || 0,
                              )
                            }
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                          <p className="text-xs text-brown mt-1">What clients receive when booking with this card.</p>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Beautician Commission (%) *</label>
                          <input
                            type="number"
                            min={0}
                            value={promo.salonCommissionPercent ?? ''}
                            onChange={(e) =>
                              updatePromoCode(
                                index,
                                'salonCommissionPercent',
                                e.target.value === '' ? null : parseFloat(e.target.value) || 0,
                              )
                            }
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                          <p className="text-xs text-brown mt-1">Commission as a percentage of the original service price.</p>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Card Usage Limit *</label>
                          <input
                            type="number"
                            min={1}
                            value={promo.salonUsageLimit ?? ''}
                            onChange={(e) =>
                              updatePromoCode(
                                index,
                                'salonUsageLimit',
                                e.target.value === '' ? null : Math.max(1, parseInt(e.target.value) || 1),
                              )
                            }
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                          <p className="text-xs text-brown mt-1">Maximum number of redemptions for this card (default 10).</p>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Redemptions Used</label>
                          <input
                            type="text"
                            value={`${promo.salonUsedCount ?? 0}${promo.salonUsageLimit ? ` / ${promo.salonUsageLimit}` : ''}`}
                            readOnly
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white text-sm text-brown-dark/70"
                          />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Commission Earned (KSH)</label>
                          <input
                            type="text"
                            value={`KSH ${(promo.commissionTotal ?? 0).toLocaleString()}`}
                            readOnly
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white text-sm text-brown-dark/70"
                          />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Commission Paid Out (KSH)</label>
                          <input
                            type="text"
                            value={`KSH ${(promo.commissionPaid ?? 0).toLocaleString()}`}
                            readOnly
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white text-sm text-brown-dark/70"
                          />
                        </div>
                      </div>
                    )}
                  </div>

                  {/* Regular Promo Code Settings (non-referral, non-salon) */}
                  {!promo.isReferral && !promo.isSalonReferral && (
                    <div className="border-t border-brown-light/40 pt-4 mt-4">
                      <div className="space-y-4">
                        <div>
                          <label className="flex items-center gap-2 text-sm font-medium text-brown-dark mb-1">
                            <input
                              type="checkbox"
                              checked={promo.allowFirstTimeClient ?? true}
                              onChange={(e) => updatePromoCode(index, 'allowFirstTimeClient', e.target.checked)}
                            />
                            Allow first-time clients to use this promo code
                          </label>
                          <p className="text-xs text-brown mt-1">
                            Uncheck this to create a card-based promo code that can only be used by returning clients. These are perfect for printed promotional cards.
                          </p>
                        </div>
                        {promo.allowFirstTimeClient === false && (
                          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                            <div className="flex items-start gap-3">
                              <svg className="w-5 h-5 text-yellow-600 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                                <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                              </svg>
                              <div className="flex-1">
                                <p className="text-sm font-semibold text-yellow-800 mb-2">Card-Based Promo Code</p>
                                <p className="text-xs text-yellow-700 mb-3">
                                  This promo code is designed for printed cards. First-time clients will not be able to use this code - they must book their first appointment first.
                                </p>
                                <Link
                                  href={`/admin/promo-codes/print?code=${encodeURIComponent(promo.code)}`}
                                  target="_blank"
                                  className="inline-flex items-center gap-2 bg-brown-dark text-white px-4 py-2 rounded-lg hover:bg-brown transition-colors text-sm font-semibold"
                                  onClick={(e) => {
                                    if (!promo.code || !promo.code.trim()) {
                                      e.preventDefault()
                                      setMessage({ type: 'error', text: 'Please enter a promo code first' })
                                    }
                                  }}
                                >
                                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                                  </svg>
                                  Generate Printable Card
                                </Link>
                              </div>
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </div>
                <button
                  onClick={() => removePromoCode(index)}
                  className="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 transition-colors"
                >
                  Remove
                </button>
              </div>
            ))}
            {promoCodes.length === 0 && (
              <div className="text-center text-brown py-8">
                No promo codes yet. Click "Add Promo Code" to create one.
              </div>
            )}
          </div>
        </div>
      </div>

      <UnsavedChangesDialog
        isOpen={showDialog}
        onSave={handleDialogSave}
        onLeave={handleDialogLeave}
        onCancel={handleDialogCancel}
        saving={saving}
      />
    </div>
  )
}

