'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import Toast from '@/components/Toast'
import UnsavedChangesDialog from '@/components/UnsavedChangesDialog'

interface PromoCode {
  code: string
  description: string
  discountType: 'percentage' | 'fixed'
  discountValue: number
  minPurchase?: number
  maxDiscount?: number | null
  validFrom: string
  validUntil: string
  usageLimit?: number | null
  usedCount: number
  active: boolean
  isReferral?: boolean
  referrerEmail?: string | null
  friendUsesRemaining?: number | null
  referrerRewardAvailable?: boolean
  allowFirstTimeClient?: boolean
  autoGenerated?: boolean
  instructionsSentAt?: string | null
  isSalonReferral?: boolean
  salonName?: string | null
  salonEmail?: string | null
  salonPartnerType?: 'salon' | 'beautician' | 'influencer'
  clientDiscountPercent?: number | null
  salonCommissionPercent?: number | null
  salonUsageLimit?: number | null
  salonUsedCount?: number
  commissionTotal?: number
  commissionPaid?: number
}

const authorizedFetch = (input: RequestInfo | URL, init: RequestInit = {}) =>
  fetch(input, { credentials: 'include', ...init })

export default function AdminPromoCodes() {
  const [promoCodes, setPromoCodes] = useState<PromoCode[]>([])
  const [originalPromoCodes, setOriginalPromoCodes] = useState<PromoCode[]>([])
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null)
  const [showDialog, setShowDialog] = useState(false)
  const [pendingNavigation, setPendingNavigation] = useState<string | null>(null)
  const router = useRouter()
  const hasUnsavedChanges = JSON.stringify(promoCodes) !== JSON.stringify(originalPromoCodes)

  useEffect(() => {
    let isMounted = true

    const checkAuth = async () => {
      try {
        const response = await authorizedFetch('/api/admin/current-user')
        if (!response.ok) {
          throw new Error('Unauthorized')
        }
        const data = await response.json()
        if (!isMounted) return
        if (!data.authenticated) {
          router.replace('/admin/login')
          return
        }
        loadPromoCodes()
      } catch (error) {
        if (!isMounted) return
        router.replace('/admin/login')
      }
    }

    checkAuth()

    return () => {
      isMounted = false
    }
  }, [router])

  const loadPromoCodes = async () => {
    try {
      const response = await authorizedFetch('/api/admin/promo-codes')
      if (response.ok) {
        const data = await response.json()
        const normalized = (data.promoCodes || []).map((promo: PromoCode) => ({
          ...promo,
          isReferral: promo.isReferral ?? false,
          referrerEmail: promo.referrerEmail ?? '',
          friendUsesRemaining:
            typeof promo.friendUsesRemaining === 'number' ? promo.friendUsesRemaining : null,
          referrerRewardAvailable: promo.referrerRewardAvailable ?? false,
          allowFirstTimeClient:
            promo.allowFirstTimeClient ?? (promo.isReferral ? true : false),
          autoGenerated: promo.autoGenerated ?? false,
          instructionsSentAt: promo.instructionsSentAt ?? null,
          isSalonReferral: promo.isSalonReferral ?? false,
          salonName: promo.salonName ?? '',
          salonEmail: promo.salonEmail ?? '',
          clientDiscountPercent:
            promo.clientDiscountPercent !== null && promo.clientDiscountPercent !== undefined
              ? promo.clientDiscountPercent
              : promo.isSalonReferral
              ? 8
              : null,
          salonCommissionPercent:
            promo.salonCommissionPercent !== null && promo.salonCommissionPercent !== undefined
              ? promo.salonCommissionPercent
              : promo.isSalonReferral
              ? 4
              : null,
          salonUsageLimit:
            promo.salonUsageLimit !== null && promo.salonUsageLimit !== undefined
              ? promo.salonUsageLimit
              : promo.isSalonReferral
              ? 10
              : null,
          salonUsedCount: promo.salonUsedCount ?? 0,
          commissionTotal: promo.commissionTotal ?? 0,
          commissionPaid: promo.commissionPaid ?? 0,
        }))
        setPromoCodes(normalized)
        setOriginalPromoCodes(normalized)
      }
    } catch (error) {
      console.error('Error loading promo codes:', error)
    } finally {
      setLoading(false)
    }
  }

  // Handle unsaved changes warning
  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (hasUnsavedChanges) {
        e.preventDefault()
        e.returnValue = ''
        return ''
      }
    }

    window.addEventListener('beforeunload', handleBeforeUnload)

    return () => {
      window.removeEventListener('beforeunload', handleBeforeUnload)
    }
  }, [hasUnsavedChanges])

  // Intercept Link clicks
  const handleLinkClick = (e: React.MouseEvent<HTMLAnchorElement>, href: string) => {
    if (hasUnsavedChanges) {
      e.preventDefault()
      setPendingNavigation(href)
      setShowDialog(true)
    }
  }

  const handleDialogSave = async () => {
    await handleSave()
    if (pendingNavigation) {
      setShowDialog(false)
      router.push(pendingNavigation)
      setPendingNavigation(null)
    }
  }

  const handleDialogLeave = () => {
    setShowDialog(false)
    if (pendingNavigation) {
      router.push(pendingNavigation)
      setPendingNavigation(null)
    }
  }

  const handleDialogCancel = () => {
    setShowDialog(false)
    setPendingNavigation(null)
  }

  const handleSave = async () => {
    setSaving(true)
    setMessage(null)

    try {
      const response = await authorizedFetch('/api/admin/promo-codes', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ promoCodes }),
      })

      if (response.ok) {
        setMessage({ type: 'success', text: 'Promo codes updated successfully!' })
        setOriginalPromoCodes(promoCodes) // Update original to clear unsaved changes flag
        setShowDialog(false) // Close dialog if open
      } else {
        setMessage({ type: 'error', text: 'Failed to save promo codes' })
      }
    } catch (error) {
      setMessage({ type: 'error', text: 'An error occurred' })
    } finally {
      setSaving(false)
    }
  }

  const addPromoCode = () => {
    setPromoCodes([
      ...promoCodes,
      {
        code: '',
        description: '',
        discountType: 'percentage',
        discountValue: 10,
        minPurchase: 0,
        maxDiscount: null,
        validFrom: new Date().toISOString().split('T')[0],
        validUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        usageLimit: null,
        usedCount: 0,
        active: true,
        isReferral: false,
        referrerEmail: '',
        friendUsesRemaining: 1,
        referrerRewardAvailable: false,
        allowFirstTimeClient: true,
        autoGenerated: false,
        instructionsSentAt: null,
        isSalonReferral: false,
        salonName: '',
        salonEmail: '',
        salonPartnerType: 'salon',
        clientDiscountPercent: 8,
        salonCommissionPercent: 4,
        salonUsageLimit: 10,
        salonUsedCount: 0,
        commissionTotal: 0,
        commissionPaid: 0,
      },
    ])
  }

  const updatePromoCode = (index: number, field: keyof PromoCode, value: any) => {
    setPromoCodes((prev) => {
      const updated = [...prev]
      const current = { ...updated[index] }

      const ensureNumber = (input: any, fallback: number | null = null) => {
        if (input === '' || input === null || input === undefined) return fallback
        const parsed = Number(input)
        return Number.isFinite(parsed) ? parsed : fallback
      }

      if (field === 'isReferral') {
        const enabled = Boolean(value)
        current.isReferral = enabled
        if (enabled) {
          current.isSalonReferral = false
          current.salonPartnerType = undefined
        }
        current.allowFirstTimeClient = enabled ? true : current.allowFirstTimeClient ?? false
        current.discountType = 'percentage'
        if (enabled && (!current.discountValue || current.discountValue < 1)) {
          current.discountValue = current.clientDiscountPercent ?? 10
        }
        if (enabled && (current.friendUsesRemaining === null || current.friendUsesRemaining === undefined)) {
          current.friendUsesRemaining = 1
        }
      } else if (field === 'isSalonReferral') {
        const enabled = Boolean(value)
        current.isSalonReferral = enabled
        if (enabled) {
          current.isReferral = false
          current.discountType = 'percentage'
          const clientDiscount = ensureNumber(current.clientDiscountPercent, 8) ?? 8
          current.clientDiscountPercent = clientDiscount
          current.discountValue = clientDiscount
          current.salonCommissionPercent = ensureNumber(current.salonCommissionPercent, 4) ?? 4
          const usageLimit = ensureNumber(current.salonUsageLimit, 10)
          current.salonUsageLimit = usageLimit === null ? 10 : usageLimit
          if (!current.usageLimit || current.usageLimit < (current.salonUsageLimit ?? 0)) {
            current.usageLimit = current.salonUsageLimit ?? current.usageLimit
          }
          current.salonName = current.salonName ?? ''
          current.salonEmail = current.salonEmail ?? ''
          current.salonPartnerType = current.salonPartnerType || 'salon'
        } else {
          current.salonPartnerType = undefined
        }
      } else if (field === 'discountValue') {
        const amount = ensureNumber(value, 0) ?? 0
        current.discountValue = amount
        if (current.isSalonReferral) {
          current.clientDiscountPercent = amount
        }
      } else if (field === 'clientDiscountPercent') {
        const amount = ensureNumber(value, null)
        current.clientDiscountPercent = amount
        if (current.isSalonReferral && amount !== null) {
          current.discountType = 'percentage'
          current.discountValue = amount
        }
      } else if (field === 'salonCommissionPercent') {
        current.salonCommissionPercent = ensureNumber(value, null)
      } else if (field === 'salonPartnerType') {
        const allowed = ['salon', 'beautician', 'influencer']
        current.salonPartnerType = allowed.includes(value) ? (value as 'salon' | 'beautician' | 'influencer') : 'salon'
      } else if (field === 'salonUsageLimit') {
        current.salonUsageLimit = ensureNumber(value, null)
        if (current.isSalonReferral && current.salonUsageLimit && (!current.usageLimit || current.usageLimit < current.salonUsageLimit)) {
          current.usageLimit = current.salonUsageLimit
        }
      } else if (field === 'usageLimit') {
        current.usageLimit = ensureNumber(value, null)
      } else if (field === 'minPurchase' || field === 'maxDiscount') {
        (current as any)[field] = ensureNumber(value, field === 'minPurchase' ? 0 : null)
      } else {
        ;(current as any)[field] = value
      }

      updated[index] = current
      return updated
    })
  }

  const removePromoCode = (index: number) => {
    setPromoCodes((prev) => prev.filter((_, i) => i !== index))
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-baby-pink-light flex items-center justify-center">
        <div className="text-brown">Loading...</div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-baby-pink-light py-8 px-4">
      <div className="max-w-6xl mx-auto">
        <div className="mb-6 flex justify-between items-center">
          {hasUnsavedChanges && (
            <div className="text-sm text-orange-600 font-medium">
              ⚠️ You have unsaved changes
            </div>
          )}
          <Link 
            href="/admin/dashboard" 
            className="text-brown hover:text-brown-dark"
            onClick={(e) => handleLinkClick(e, '/admin/dashboard')}
          >
            ← Back to Dashboard
          </Link>
          <div className="flex gap-4">
            <button
              onClick={addPromoCode}
              className="bg-brown-dark text-white px-6 py-2 rounded-lg hover:bg-brown transition-colors"
            >
              + Add Promo Code
            </button>
            <button
              onClick={handleSave}
              disabled={saving}
              className="bg-brown-dark text-white px-6 py-2 rounded-lg hover:bg-brown transition-colors disabled:opacity-50"
            >
              {saving ? 'Saving...' : 'Save Changes'}
            </button>
          </div>
        </div>

        {/* Toast Notification */}
        {message && (
          <Toast
            message={message.text}
            type={message.type}
            onClose={() => setMessage(null)}
          />
        )}

        <div className="bg-white rounded-lg shadow-lg p-8">
          <h1 className="text-4xl font-display text-brown-dark mb-8">Promo Codes Management</h1>
          <div className="space-y-6">
            {promoCodes.map((promo, index) => (
              <div key={index} className="bg-pink-light rounded-lg p-6 space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Code *</label>
                    <input
                      type="text"
                      value={promo.code}
                      onChange={(e) => updatePromoCode(index, 'code', e.target.value.toUpperCase())}
                      placeholder="REFER10"
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Description</label>
                    <input
                      type="text"
                      value={promo.description}
                      onChange={(e) => updatePromoCode(index, 'description', e.target.value)}
                      placeholder="10% off for referrals"
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Discount Type</label>
                    <select
                      value={promo.discountType}
                      onChange={(e) => updatePromoCode(index, 'discountType', e.target.value)}
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    >
                      <option value="percentage">Percentage</option>
                      <option value="fixed">Fixed Amount (KSH)</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Discount Value *</label>
                    <input
                      type="number"
                      value={promo.discountValue}
                      onChange={(e) => updatePromoCode(index, 'discountValue', parseFloat(e.target.value) || 0)}
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Min Purchase (KSH)</label>
                    <input
                      type="number"
                      value={promo.minPurchase || 0}
                      onChange={(e) => updatePromoCode(index, 'minPurchase', parseFloat(e.target.value) || 0)}
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Max Discount (KSH, leave empty for no limit)</label>
                    <input
                      type="number"
                      value={promo.maxDiscount || ''}
                      onChange={(e) => updatePromoCode(index, 'maxDiscount', e.target.value ? parseFloat(e.target.value) : null)}
                      placeholder="No limit"
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Valid From *</label>
                    <input
                      type="date"
                      value={promo.validFrom}
                      onChange={(e) => updatePromoCode(index, 'validFrom', e.target.value)}
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Valid Until *</label>
                    <input
                      type="date"
                      value={promo.validUntil}
                      onChange={(e) => updatePromoCode(index, 'validUntil', e.target.value)}
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brown-dark mb-1">Usage Limit (leave empty for unlimited)</label>
                    <input
                      type="number"
                      value={promo.usageLimit || ''}
                      onChange={(e) => updatePromoCode(index, 'usageLimit', e.target.value ? parseInt(e.target.value) : null)}
                      placeholder="Unlimited"
                      className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                    />
                  </div>
                  <div className="flex items-end gap-4">
                    <label className="flex items-center">
                      <input
                        type="checkbox"
                        checked={promo.active}
                        onChange={(e) => updatePromoCode(index, 'active', e.target.checked)}
                        className="mr-2"
                      />
                      <span className="text-sm font-medium text-brown-dark">Active</span>
                    </label>
                    <div className="text-sm text-brown">
                      Used: {promo.usedCount} {promo.usageLimit ? `/ ${promo.usageLimit}` : ''}
                    </div>
                  </div>
                </div>
                <div className="md:col-span-2 border-t border-brown-light/40 pt-4 mt-2 space-y-6">
                  <div>
                    <div className="flex items-center gap-2 text-sm font-semibold text-brown-dark">
                      <label className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={promo.isReferral || false}
                          onChange={(e) => updatePromoCode(index, 'isReferral', e.target.checked)}
                        />
                        Client referral (friend-to-friend)
                      </label>
                    </div>
                    <p className="text-xs text-brown mt-1">
                      Clients can give friends a 10% welcome discount. Once their friend books, the client unlocks their own reward.
                    </p>
                    {(promo.isReferral || false) && (
                      <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">
                            Referrer Email *
                          </label>
                          <input
                            type="email"
                            value={promo.referrerEmail || ''}
                            onChange={(e) => updatePromoCode(index, 'referrerEmail', e.target.value)}
                            placeholder="client@example.com"
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">
                            Friend Uses Remaining
                          </label>
                          <input
                            type="number"
                            min={0}
                            value={promo.friendUsesRemaining ?? 1}
                            onChange={(e) =>
                              updatePromoCode(
                                index,
                                'friendUsesRemaining',
                                e.target.value === '' ? null : Math.max(0, parseInt(e.target.value) || 0),
                              )
                            }
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                          <p className="text-xs text-brown mt-1">How many friends can redeem this code (usually 1).</p>
                        </div>
                        <div>
                          <label className="flex items-center gap-2 text-sm font-medium text-brown-dark mb-1">
                            <input
                              type="checkbox"
                              checked={promo.referrerRewardAvailable || false}
                              onChange={(e) => updatePromoCode(index, 'referrerRewardAvailable', e.target.checked)}
                            />
                            Referrer reward still available
                          </label>
                          <p className="text-xs text-brown mt-1">
                            Keep this checked until the referrer uses the code for their own discount.
                          </p>
                        </div>
                        <div>
                          <label className="flex items-center gap-2 text-sm font-medium text-brown-dark mb-1">
                            <input
                              type="checkbox"
                              checked={promo.allowFirstTimeClient ?? true}
                              onChange={(e) => updatePromoCode(index, 'allowFirstTimeClient', e.target.checked)}
                            />
                            Allow first-time clients to use
                          </label>
                          <p className="text-xs text-brown mt-1">
                            Enable so new clients can redeem referral codes even on their first visit.
                          </p>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">
                            Instructions last sent
                          </label>
                          <input
                            type="text"
                            value={promo.instructionsSentAt ? new Date(promo.instructionsSentAt).toLocaleString() : 'Never'}
                            readOnly
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white text-sm text-brown-dark/70"
                          />
                        </div>
                      </div>
                    )}
                  </div>

                  <div className="border-t border-brown-light/40 pt-4">
                    <div className="flex items-center gap-2 text-sm font-semibold text-brown-dark">
                      <label className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={promo.isSalonReferral || false}
                          onChange={(e) => updatePromoCode(index, 'isSalonReferral', e.target.checked)}
                        />
                        Partner referral cards (salon / beautician / influencer)
                      </label>
                    </div>
                    <p className="text-xs text-brown mt-1">
                      Issue up to 10 cards per partner. New clients get a discount and your partner earns commission once the booking is confirmed.
                    </p>
                    {(promo.isSalonReferral || false) && (
                      <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Partner Type *</label>
                          <select
                            value={promo.salonPartnerType || 'salon'}
                            onChange={(e) =>
                              updatePromoCode(
                                index,
                                'salonPartnerType',
                                (['salon', 'beautician', 'influencer'].includes(e.target.value)
                                  ? e.target.value
                                  : 'salon') as 'salon' | 'beautician' | 'influencer',
                              )
                            }
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          >
                            <option value="salon">Salon</option>
                            <option value="beautician">Beautician</option>
                            <option value="influencer">Influencer / Creator</option>
                          </select>
                          <p className="text-xs text-brown mt-1">
                            Used for onboarding emails and partner reporting.
                          </p>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Partner Name *</label>
                          <input
                            type="text"
                            value={promo.salonName || ''}
                            onChange={(e) => updatePromoCode(index, 'salonName', e.target.value)}
                            placeholder="Glow Beauty Studio"
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Partner Contact Email *</label>
                          <input
                            type="email"
                            value={promo.salonEmail || ''}
                            onChange={(e) => updatePromoCode(index, 'salonEmail', e.target.value)}
                            placeholder="beautician@example.com"
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Client Discount (%) *</label>
                          <input
                            type="number"
                            min={0}
                            value={promo.clientDiscountPercent ?? ''}
                            onChange={(e) =>
                              updatePromoCode(
                                index,
                                'clientDiscountPercent',
                                e.target.value === '' ? null : parseFloat(e.target.value) || 0,
                              )
                            }
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                          <p className="text-xs text-brown mt-1">What clients receive when booking with this card.</p>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Beautician Commission (%) *</label>
                          <input
                            type="number"
                            min={0}
                            value={promo.salonCommissionPercent ?? ''}
                            onChange={(e) =>
                              updatePromoCode(
                                index,
                                'salonCommissionPercent',
                                e.target.value === '' ? null : parseFloat(e.target.value) || 0,
                              )
                            }
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                          <p className="text-xs text-brown mt-1">Commission as a percentage of the original service price.</p>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Card Usage Limit *</label>
                          <input
                            type="number"
                            min={1}
                            value={promo.salonUsageLimit ?? ''}
                            onChange={(e) =>
                              updatePromoCode(
                                index,
                                'salonUsageLimit',
                                e.target.value === '' ? null : Math.max(1, parseInt(e.target.value) || 1),
                              )
                            }
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white"
                          />
                          <p className="text-xs text-brown mt-1">Maximum number of redemptions for this card (default 10).</p>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Redemptions Used</label>
                          <input
                            type="text"
                            value={`${promo.salonUsedCount ?? 0}${promo.salonUsageLimit ? ` / ${promo.salonUsageLimit}` : ''}`}
                            readOnly
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white text-sm text-brown-dark/70"
                          />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Commission Earned (KSH)</label>
                          <input
                            type="text"
                            value={`KSH ${(promo.commissionTotal ?? 0).toLocaleString()}`}
                            readOnly
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white text-sm text-brown-dark/70"
                          />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-brown-dark mb-1">Commission Paid Out (KSH)</label>
                          <input
                            type="text"
                            value={`KSH ${(promo.commissionPaid ?? 0).toLocaleString()}`}
                            readOnly
                            className="w-full px-3 py-2 border border-brown-light rounded bg-white text-sm text-brown-dark/70"
                          />
                        </div>
                      </div>
                    )}
                  </div>

                  {/* Regular Promo Code Settings (non-referral, non-salon) */}
                  {!promo.isReferral && !promo.isSalonReferral && (
                    <div className="border-t border-brown-light/40 pt-4 mt-4">
                      <div className="space-y-4">
                        <div>
                          <label className="flex items-center gap-2 text-sm font-medium text-brown-dark mb-1">
                            <input
                              type="checkbox"
                              checked={promo.allowFirstTimeClient ?? true}
                              onChange={(e) => updatePromoCode(index, 'allowFirstTimeClient', e.target.checked)}
                            />
                            Allow first-time clients to use this promo code
                          </label>
                          <p className="text-xs text-brown mt-1">
                            Uncheck this to create a card-based promo code that can only be used by returning clients. These are perfect for printed promotional cards.
                          </p>
                        </div>
                        {promo.allowFirstTimeClient === false && (
                          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                            <div className="flex items-start gap-3">
                              <svg className="w-5 h-5 text-yellow-600 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                                <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                              </svg>
                              <div className="flex-1">
                                <p className="text-sm font-semibold text-yellow-800 mb-2">Card-Based Promo Code</p>
                                <p className="text-xs text-yellow-700 mb-3">
                                  This promo code is designed for printed cards. First-time clients will not be able to use this code - they must book their first appointment first.
                                </p>
                                <Link
                                  href={`/admin/promo-codes/print?code=${encodeURIComponent(promo.code)}`}
                                  target="_blank"
                                  className="inline-flex items-center gap-2 bg-brown-dark text-white px-4 py-2 rounded-lg hover:bg-brown transition-colors text-sm font-semibold"
                                  onClick={(e) => {
                                    if (!promo.code || !promo.code.trim()) {
                                      e.preventDefault()
                                      setMessage({ type: 'error', text: 'Please enter a promo code first' })
                                    }
                                  }}
                                >
                                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                                  </svg>
                                  Generate Printable Card
                                </Link>
                              </div>
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </div>
                <button
                  onClick={() => removePromoCode(index)}
                  className="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 transition-colors"
                >
                  Remove
                </button>
              </div>
            ))}
            {promoCodes.length === 0 && (
              <div className="text-center text-brown py-8">
                No promo codes yet. Click "Add Promo Code" to create one.
              </div>
            )}
          </div>
        </div>
      </div>

      <UnsavedChangesDialog
        isOpen={showDialog}
        onSave={handleDialogSave}
        onLeave={handleDialogLeave}
        onCancel={handleDialogCancel}
        saving={saving}
      />
    </div>
  )
}

