export type PromoCode = {
  code: string
  description?: string
  discountType: 'percentage' | 'fixed'
  discountValue: number
  minPurchase?: number
  maxDiscount?: number | null
  validFrom?: string
  validUntil?: string
  usageLimit?: number | null
  usedCount?: number
  active?: boolean
  isReferral?: boolean
  referrerEmail?: string | null
  friendUsesRemaining?: number | null
  referrerRewardAvailable?: boolean
  friendDiscountEnabled?: boolean
  friendDiscountPercent?: number | null
  referrerRewardPercent?: number | null
  friendReferralLimit?: number | null
  friendRedemptionCount?: number
  referrerRewardRedeemedCount?: number
  referralValidDays?: number | null
  referrerName?: string | null
  allowFirstTimeClient?: boolean
  autoGenerated?: boolean
  instructionsSentAt?: string | null
  isSalonReferral?: boolean
  salonName?: string | null
  salonEmail?: string | null
  salonPartnerType?: 'salon' | 'beautician' | 'influencer'
  clientDiscountEnabled?: boolean
  clientDiscountPercent?: number | null
  clientDiscountAmount?: number | null
  salonCommissionType?: 'percentage' | 'fixed'
  salonCommissionPercent?: number | null
  salonCommissionAmount?: number | null
  salonUsageLimit?: number | null
  salonUsedCount?: number
  commissionTotal?: number
  commissionPaid?: number
  terminatedAt?: string | null
  usedByEmails?: string[] // Track which emails have used this promo code (one-time use per email)
}

export type PromoCatalog = {
  promoCodes: PromoCode[]
}

const coerceNumber = (value: unknown, fallback: number) => {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return value
  }
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : fallback
}

export const normalizePromoCatalog = (raw: any): { catalog: PromoCatalog; changed: boolean; count: number } => {
  const promoCodesArray: any[] = Array.isArray(raw?.promoCodes) ? raw.promoCodes : Array.isArray(raw) ? raw : []
  let changed = false

  const promoCodes: PromoCode[] = promoCodesArray.map((promo) => {
    const isSalonReferral = promo?.isSalonReferral === true
    const partnerType: 'salon' | 'beautician' | 'influencer' =
      typeof promo?.salonPartnerType === 'string' &&
      ['salon', 'beautician', 'influencer'].includes(promo.salonPartnerType)
        ? promo.salonPartnerType
        : 'salon'

    const normalized: PromoCode = {
      code: typeof promo?.code === 'string' ? promo.code.trim().toUpperCase() : '',
      description: typeof promo?.description === 'string' ? promo.description : '',
      discountType: promo?.discountType === 'fixed' ? 'fixed' : 'percentage',
      discountValue: coerceNumber(promo?.discountValue, 0),
      minPurchase: coerceNumber(promo?.minPurchase, 0),
      maxDiscount: promo?.maxDiscount === null || promo?.maxDiscount === undefined ? null : coerceNumber(promo.maxDiscount, 0),
      validFrom: typeof promo?.validFrom === 'string' ? promo.validFrom : '',
      validUntil: typeof promo?.validUntil === 'string' ? promo.validUntil : '',
      usageLimit: promo?.usageLimit === null || promo?.usageLimit === undefined ? null : coerceNumber(promo.usageLimit, 0),
      usedCount: coerceNumber(promo?.usedCount, 0),
      active: promo?.active !== false,
      isReferral: promo?.isReferral === true,
      referrerEmail:
        typeof promo?.referrerEmail === 'string' && promo.referrerEmail.trim().length > 0
          ? promo.referrerEmail.trim().toLowerCase()
          : null,
      friendUsesRemaining:
        promo?.friendUsesRemaining === null || promo?.friendUsesRemaining === undefined
          ? null
          : coerceNumber(promo.friendUsesRemaining, 0),
      friendReferralLimit:
        promo?.friendReferralLimit === null || promo?.friendReferralLimit === undefined
          ? promo?.isReferral === true
            ? 1
            : null
          : Math.max(0, coerceNumber(promo.friendReferralLimit, 1)),
      friendRedemptionCount:
        promo?.friendRedemptionCount === undefined
          ? promo?.referrerRewardAvailable === true
            ? 1
            : 0
          : Math.max(0, coerceNumber(promo.friendRedemptionCount, 0)),
      referrerRewardRedeemedCount: Math.max(0, coerceNumber(promo?.referrerRewardRedeemedCount, 0)),
      referralValidDays:
        promo?.referralValidDays === null || promo?.referralValidDays === undefined
          ? null
          : Math.max(1, coerceNumber(promo.referralValidDays, 30)),
      referrerRewardAvailable: promo?.referrerRewardAvailable === true,
      friendDiscountEnabled:
        promo?.friendDiscountEnabled === false
          ? false
          : promo?.isReferral === true
            ? promo?.friendDiscountEnabled !== false
            : undefined,
      friendDiscountPercent:
        promo?.friendDiscountPercent === null || promo?.friendDiscountPercent === undefined
          ? null
          : coerceNumber(promo.friendDiscountPercent, 0),
      referrerRewardPercent:
        promo?.referrerRewardPercent === null || promo?.referrerRewardPercent === undefined
          ? null
          : coerceNumber(promo.referrerRewardPercent, 0),
      referrerName:
        typeof promo?.referrerName === 'string' && promo.referrerName.trim().length > 0
          ? promo.referrerName.trim()
          : null,
      allowFirstTimeClient: promo?.allowFirstTimeClient !== false,
      autoGenerated: promo?.autoGenerated === true,
      instructionsSentAt: typeof promo?.instructionsSentAt === 'string' ? promo.instructionsSentAt : null,
      isSalonReferral,
      salonName:
        isSalonReferral && typeof promo?.salonName === 'string' && promo.salonName.trim().length > 0
          ? promo.salonName.trim()
          : null,
      salonEmail:
        isSalonReferral && typeof promo?.salonEmail === 'string' && promo.salonEmail.trim().length > 0
          ? promo.salonEmail.trim().toLowerCase()
          : null,
      salonPartnerType: isSalonReferral ? partnerType : undefined,
      clientDiscountEnabled:
        isSalonReferral && promo?.clientDiscountEnabled === false
          ? false
          : isSalonReferral
          ? coerceNumber(promo?.clientDiscountPercent, 0) > 0 ||
            coerceNumber(promo?.clientDiscountAmount, 0) > 0 ||
            coerceNumber(promo?.discountValue, 0) > 0
          : undefined,
      clientDiscountPercent:
        isSalonReferral && promo?.clientDiscountPercent !== null && promo?.clientDiscountPercent !== undefined
          ? coerceNumber(promo.clientDiscountPercent, 0)
          : isSalonReferral &&
            promo?.discountType !== 'fixed' &&
            promo?.clientDiscountEnabled !== false &&
            coerceNumber(promo?.discountValue, 0) > 0
          ? coerceNumber(promo.discountValue, 0)
          : null,
      clientDiscountAmount:
        isSalonReferral && promo?.clientDiscountAmount !== null && promo?.clientDiscountAmount !== undefined
          ? coerceNumber(promo.clientDiscountAmount, 0)
          : isSalonReferral &&
            promo?.discountType === 'fixed' &&
            promo?.clientDiscountEnabled !== false &&
            coerceNumber(promo?.discountValue, 0) > 0
          ? coerceNumber(promo.discountValue, 0)
          : null,
      salonCommissionType: isSalonReferral && promo?.salonCommissionType === 'fixed' ? 'fixed' : 'percentage',
      salonCommissionPercent:
        isSalonReferral && promo?.salonCommissionPercent !== null && promo?.salonCommissionPercent !== undefined
          ? coerceNumber(promo.salonCommissionPercent, 0)
          : isSalonReferral && promo?.salonCommissionType !== 'fixed'
          ? 4
          : null,
      salonCommissionAmount:
        isSalonReferral && promo?.salonCommissionAmount !== null && promo?.salonCommissionAmount !== undefined
          ? coerceNumber(promo.salonCommissionAmount, 0)
          : null,
      salonUsageLimit:
        isSalonReferral && promo?.salonUsageLimit !== null && promo?.salonUsageLimit !== undefined
          ? coerceNumber(promo.salonUsageLimit, 10)
          : isSalonReferral
          ? 10
          : null,
      salonUsedCount: coerceNumber(promo?.salonUsedCount, 0),
      commissionTotal: coerceNumber(promo?.commissionTotal, 0),
      commissionPaid: coerceNumber(promo?.commissionPaid, 0),
      terminatedAt: typeof promo?.terminatedAt === 'string' ? promo.terminatedAt : null,
      usedByEmails: Array.isArray(promo?.usedByEmails)
        ? promo.usedByEmails
            .map((email: any) => (typeof email === 'string' ? email.trim().toLowerCase() : ''))
            .filter((email: string) => email.length > 0 && email.includes('@'))
        : [],
    }

    if (normalized.isReferral && !normalized.isSalonReferral) {
      const limit = normalized.friendReferralLimit ?? 1
      const redeemed = normalized.friendRedemptionCount ?? 0
      const rewardRedeemed = normalized.referrerRewardRedeemedCount ?? 0
      normalized.friendUsesRemaining =
        promo?.friendUsesRemaining === null || promo?.friendUsesRemaining === undefined
          ? Math.max(0, limit - redeemed)
          : normalized.friendUsesRemaining
      normalized.referrerRewardAvailable = redeemed > rewardRedeemed
    }

    if (normalized.code !== promo?.code) {
      changed = true
    }

    return normalized
  })

  const catalog = { promoCodes }
  return { catalog, changed, count: promoCodes.length }
}