export type PromoCode = {
  code: string
  description?: string
  discountType: 'percentage' | 'fixed'
  discountValue: number
  minPurchase?: number
  maxDiscount?: number | null
  validFrom?: string
  validUntil?: string
  usageLimit?: number | null
  usedCount?: number
  active?: boolean
  isReferral?: boolean
  referrerEmail?: string | null
  friendUsesRemaining?: number | null
  referrerRewardAvailable?: boolean
  allowFirstTimeClient?: boolean
  autoGenerated?: boolean
  instructionsSentAt?: string | null
  isSalonReferral?: boolean
  salonName?: string | null
  salonEmail?: string | null
  salonPartnerType?: 'salon' | 'beautician' | 'influencer'
  clientDiscountPercent?: number | null
  salonCommissionPercent?: number | null
  salonUsageLimit?: number | null
  salonUsedCount?: number
  commissionTotal?: number
  commissionPaid?: number
  terminatedAt?: string | null
}

export type PromoCatalog = {
  promoCodes: PromoCode[]
}

const coerceNumber = (value: unknown, fallback: number) => {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return value
  }
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : fallback
}

export const normalizePromoCatalog = (raw: any): { catalog: PromoCatalog; changed: boolean; count: number } => {
  const promoCodesArray: any[] = Array.isArray(raw?.promoCodes) ? raw.promoCodes : Array.isArray(raw) ? raw : []
  let changed = false

  const promoCodes: PromoCode[] = promoCodesArray.map((promo) => {
    const isSalonReferral = promo?.isSalonReferral === true
    const partnerType: 'salon' | 'beautician' | 'influencer' =
      typeof promo?.salonPartnerType === 'string' &&
      ['salon', 'beautician', 'influencer'].includes(promo.salonPartnerType)
        ? promo.salonPartnerType
        : 'salon'

    const normalized: PromoCode = {
      code: typeof promo?.code === 'string' ? promo.code.trim().toUpperCase() : '',
      description: typeof promo?.description === 'string' ? promo.description : '',
      discountType: promo?.discountType === 'fixed' ? 'fixed' : 'percentage',
      discountValue: coerceNumber(promo?.discountValue, 0),
      minPurchase: coerceNumber(promo?.minPurchase, 0),
      maxDiscount: promo?.maxDiscount === null || promo?.maxDiscount === undefined ? null : coerceNumber(promo.maxDiscount, 0),
      validFrom: typeof promo?.validFrom === 'string' ? promo.validFrom : '',
      validUntil: typeof promo?.validUntil === 'string' ? promo.validUntil : '',
      usageLimit: promo?.usageLimit === null || promo?.usageLimit === undefined ? null : coerceNumber(promo.usageLimit, 0),
      usedCount: coerceNumber(promo?.usedCount, 0),
      active: promo?.active !== false,
      isReferral: promo?.isReferral === true,
      referrerEmail:
        typeof promo?.referrerEmail === 'string' && promo.referrerEmail.trim().length > 0
          ? promo.referrerEmail.trim().toLowerCase()
          : null,
      friendUsesRemaining:
        promo?.friendUsesRemaining === null || promo?.friendUsesRemaining === undefined
          ? null
          : coerceNumber(promo.friendUsesRemaining, 0),
      referrerRewardAvailable: promo?.referrerRewardAvailable === true,
      allowFirstTimeClient: promo?.allowFirstTimeClient !== false,
      autoGenerated: promo?.autoGenerated === true,
      instructionsSentAt: typeof promo?.instructionsSentAt === 'string' ? promo.instructionsSentAt : null,
      isSalonReferral,
      salonName:
        isSalonReferral && typeof promo?.salonName === 'string' && promo.salonName.trim().length > 0
          ? promo.salonName.trim()
          : null,
      salonEmail:
        isSalonReferral && typeof promo?.salonEmail === 'string' && promo.salonEmail.trim().length > 0
          ? promo.salonEmail.trim().toLowerCase()
          : null,
      salonPartnerType: isSalonReferral ? partnerType : undefined,
      clientDiscountPercent:
        isSalonReferral && promo?.clientDiscountPercent !== null && promo?.clientDiscountPercent !== undefined
          ? coerceNumber(promo.clientDiscountPercent, 0)
          : isSalonReferral
          ? 8
          : null,
      salonCommissionPercent:
        isSalonReferral && promo?.salonCommissionPercent !== null && promo?.salonCommissionPercent !== undefined
          ? coerceNumber(promo.salonCommissionPercent, 0)
          : isSalonReferral
          ? 4
          : null,
      salonUsageLimit:
        isSalonReferral && promo?.salonUsageLimit !== null && promo?.salonUsageLimit !== undefined
          ? coerceNumber(promo.salonUsageLimit, 10)
          : isSalonReferral
          ? 10
          : null,
      salonUsedCount: coerceNumber(promo?.salonUsedCount, 0),
      commissionTotal: coerceNumber(promo?.commissionTotal, 0),
      commissionPaid: coerceNumber(promo?.commissionPaid, 0),
      terminatedAt: typeof promo?.terminatedAt === 'string' ? promo.terminatedAt : null,
    }

    if (normalized.code !== promo?.code) {
      changed = true
    }

    return normalized
  })

  const catalog = { promoCodes }
  return { catalog, changed, count: promoCodes.length }
}


