import { NextRequest, NextResponse } from 'next/server'
import { revalidatePath } from 'next/cache'
import { requireAdminAuth, getAdminUser } from '@/lib/admin-auth'
import {
  loadPartnerOnboardingRecords,
  updatePartnerOnboardingRecord,
  PartnerOnboardingRecord,
  resolvePartnerReferralConfig,
} from '@/lib/partner-onboarding-utils'
import { readDataFile, writeDataFile } from '@/lib/data-utils'
import { normalizePromoCatalog, PromoCode } from '@/lib/promo-utils'
import { sendPartnerOnboardingEmail } from '@/lib/email/send-partner-onboarding'
import { recordActivity } from '@/lib/activity-log'
import { loadPolicies } from '@/lib/policies-utils'

const studioContactEmail = process.env.CALENDAR_EMAIL || 'hello@lashdiary.co.ke'

type PromoCatalogFile = {
  promoCodes: any[]
}

function slugifyBusinessName(input: string) {
  return input
    .toUpperCase()
    .replace(/[^A-Z0-9]/g, '')
    .slice(0, 8)
}

function generatePartnerCode(base: string, existingCodes: Set<string>) {
  const prefix = base.length >= 3 ? base : `LD${base}`.slice(0, 6)
  let attempt = `${prefix}${Math.floor(Math.random() * 900 + 100)}`
  let tries = 0
  while (existingCodes.has(attempt) && tries < 20) {
    attempt = `${prefix}${Math.floor(Math.random() * 900 + 100)}`
    tries += 1
  }
  if (existingCodes.has(attempt)) {
    let suffix = 1
    while (existingCodes.has(`${prefix}${suffix}`) && suffix < 1000) {
      suffix += 1
    }
    return `${prefix}${suffix}`.slice(0, 10)
  }
  return attempt.slice(0, 10)
}

type TemplateContext = Record<string, string | number>

function renderWithTokens(template: string, context: TemplateContext) {
  return template.replace(/\{\{\s*([\w]+)\s*\}\}/g, (match, token) => {
    const value = context[token]
    return value === undefined || value === null ? '' : String(value)
  })
}

async function ensurePromoCode(
  record: PartnerOnboardingRecord,
  commissionPercent: number,
  referralConfig: ReturnType<typeof resolvePartnerReferralConfig>,
) {
  const promoRaw = await readDataFile<PromoCatalogFile>('promo-codes.json', { promoCodes: [] })
  const { catalog } = normalizePromoCatalog(promoRaw)
  const existingSet = new Set(catalog.promoCodes.map((promo) => promo.code))

  const discountPercent = referralConfig.clientDiscountPercent
  const codeValidDays = referralConfig.codeValidDays
  const redeemLimit = referralConfig.redeemLimit

  const now = new Date()
  const validUntilDate = new Date(now)
  validUntilDate.setDate(validUntilDate.getDate() + codeValidDays)
  const validUntil = validUntilDate.toISOString().split('T')[0]
  const validFrom = now.toISOString().split('T')[0]

  const promoCodeValue =
    record.promoCode && existingSet.has(record.promoCode) ? record.promoCode : generatePartnerCode(slugifyBusinessName(record.businessName), existingSet)

  const promoIndex = catalog.promoCodes.findIndex((promo) => promo.code === promoCodeValue)
  const existingPromo = promoIndex === -1 ? null : catalog.promoCodes[promoIndex]

  const updatedPromo: PromoCode = {
    ...existingPromo,
    code: promoCodeValue,
    description: `Partner referral for ${record.businessName}`,
    discountType: 'percentage',
    discountValue: discountPercent,
    minPurchase: existingPromo?.minPurchase ?? 0,
    maxDiscount: existingPromo?.maxDiscount ?? null,
    validFrom: existingPromo?.validFrom ?? validFrom,
    validUntil,
    usageLimit: redeemLimit,
    usedCount: existingPromo?.usedCount ?? 0,
    active: true,
    isReferral: true,
    referrerEmail: record.email,
    friendUsesRemaining: existingPromo?.friendUsesRemaining ?? null,
    referrerRewardAvailable: existingPromo?.referrerRewardAvailable ?? false,
    allowFirstTimeClient: true,
    autoGenerated: true,
    instructionsSentAt: existingPromo?.instructionsSentAt ?? null,
    isSalonReferral: true,
    salonName: record.businessName,
    salonEmail: record.email,
    salonPartnerType: record.partnerType,
    clientDiscountPercent: discountPercent,
    salonCommissionPercent: commissionPercent,
    salonUsageLimit: redeemLimit,
    salonUsedCount: existingPromo?.salonUsedCount ?? 0,
    commissionTotal: existingPromo?.commissionTotal ?? 0,
    commissionPaid: existingPromo?.commissionPaid ?? 0,
  }

  if (promoIndex === -1) {
    catalog.promoCodes.push(updatedPromo)
  } else {
    catalog.promoCodes[promoIndex] = updatedPromo
  }

  await writeDataFile('promo-codes.json', catalog)
  return {
    code: promoCodeValue,
    validUntilIso: updatedPromo.validUntil ?? validUntil,
    validFromIso: updatedPromo.validFrom ?? validFrom,
  }
}

function buildDetailsEmail({
  partner,
  promoCode,
  validUntil,
  referralConfig,
  studioEmail,
}: {
  partner: PartnerOnboardingRecord
  promoCode: string
  validUntil: string
  referralConfig: ReturnType<typeof resolvePartnerReferralConfig>
  studioEmail: string
}) {
  const firstName = partner.contactName.split(' ')[0]
  const overrides = partner.emailOverrides ?? {}

  const context: TemplateContext = {
    firstName,
    promoCode,
    validUntil,
    commissionPercent: referralConfig.commissionPercent,
    clientDiscountPercent: referralConfig.clientDiscountPercent,
    codeValidDays: referralConfig.codeValidDays,
    redeemLimit: referralConfig.redeemLimit,
    paymentMethod: referralConfig.paymentMethod,
    studioEmail,
    businessName: partner.businessName,
  }

  const defaultSubject = 'Welcome to the Partner Referral Program'

  const defaultHtml = `
    <div style="font-family: 'Helvetica Neue', Arial, sans-serif; padding: 32px; background: #FDF9F4; color: #3E2A20;">
      <h2 style="margin-top: 0; color: #7C4B31;">Welcome to the Partner Referral Program</h2>
      <p>Hi {{firstName}},</p>
      <p>We’re thrilled to have you as part of our referral family! Here’s how your exclusive code works:</p>
      <h3 style="color:#7C4B31;">Commission</h3>
      <p>You’ll earn <strong>{{commissionPercent}}% of the total service price</strong> for every client who books using your promo code — once the service is completed.</p>
      <h3 style="color:#7C4B31;">Payment</h3>
      <p>Commissions are processed and paid every two weeks via {{paymentMethod}}.</p>
      <h3 style="color:#7C4B31;">Your Promo Code</h3>
      <div style="background:#FFFFFF;border-radius:12px;padding:16px 24px;border:1px dashed #7C4B31;display:inline-block;font-size:26px;font-weight:700;letter-spacing:4px;color:#7C4B31;">
        {{promoCode}}
      </div>
      <p style="margin-top:16px;">Each code comes with <strong>{{redeemLimit}} available slots</strong> and will remain active for <strong>{{codeValidDays}} days</strong> from the issue date (until {{validUntil}}). We’ll refresh or extend it based on your performance and engagement.</p>
      <p style="margin-top:12px;">Every client who uses your code automatically enjoys <strong>{{clientDiscountPercent}}% off</strong> their service total.</p>
      <h3 style="color:#7C4B31;">Important Details</h3>
      <ul style="line-height:1.6;">
        <li>Your referred clients receive an automatic {{clientDiscountPercent}}% discount on the service they choose.</li>
        <li>Commissions apply only to completed appointments.</li>
        <li>If a client cancels or reschedules outside our policy window, no commission applies.</li>
        <li>You’ll receive updates via email whenever a client books, completes a service, or your code is close to expiring.</li>
        <li>Your referral dashboard keeps a live view of pending and completed referrals.</li>
      </ul>
      <h3 style="color:#7C4B31;">Program Guidelines</h3>
      <p>We reserve the right to pause or terminate a promo code at any time if there’s misuse, false advertising, unprofessional conduct, sharing client information without consent, or any fraudulent activity.</p>
      <p>If a code is paused, we’ll notify you by email. Repeated violations may lead to permanent removal from the program.</p>
      <p>We’re building this program on trust, transparency, and mutual respect — and we’re thrilled to have you on board.</p>
      <p>Thank you for helping us grow our salon community — your referrals mean a lot to us and we can’t wait to celebrate your success.</p>
      <p style="margin-top:24px;">Warmly,<br/>Catherine &amp; the LashDiary Team</p>
      <hr style="margin:32px 0;border:none;border-top:1px solid #EADFD6;" />
      <p style="font-size:14px;color:#7C4B31;">Need support? Reply to this email or reach us at <a href="mailto:{{studioEmail}}" style="color:#7C4B31;">{{studioEmail}}</a>.</p>
    </div>
  `.replace(/\n\s+/g, '\n')

  const defaultText = [
    'Welcome to the Partner Referral Program',
    '',
    'Hi {{firstName}},',
    '',
    'We’re thrilled to have you as part of our referral family! Here’s how your exclusive code works:',
    '',
    'Commission:',
    '• You’ll earn {{commissionPercent}}% of the total service price for every client who books using your promo code — once the service is completed.',
    '',
    'Payment:',
    '• Commissions are processed and paid every two weeks via {{paymentMethod}}.',
    '',
    'Your promo code:',
    '• {{promoCode}}',
    '• Active for {{codeValidDays}} days (until {{validUntil}}) with {{redeemLimit}} available slots.',
    '',
    'Client perks:',
    '• Every client who uses your code unlocks a {{clientDiscountPercent}}% discount on their service.',
    '',
    'Important details:',
    '• Commissions apply only to completed appointments.',
    '• If a client cancels outside our policy window, no commission applies.',
    '• You’ll receive updates when someone books, completes a service, or your code is close to expiring.',
    '• Check your referral dashboard anytime for pending and completed referrals.',
    '',
    'Program guidelines:',
    '• We may pause or terminate a code for misuse, self-use, misrepresentation, unprofessional behavior, sharing client information without consent, or any fraudulent/inappropriate activity.',
    '• We’ll email you if a code is paused. Repeated violations can lead to permanent removal.',
    '• We rely on trust, transparency, and mutual respect—and we’re excited to grow together.',
    '',
    'Thank you for growing our community — we can’t wait to celebrate your success.',
    '',
    'Warmly,',
    'Catherine & the LashDiary Team',
    '{{studioEmail}}',
  ].join('\n')

  const subjectTemplate = overrides.detailsSubject || defaultSubject
  const htmlTemplate = overrides.detailsBodyHtml || defaultHtml
  const textTemplate = overrides.detailsBodyText || defaultText

  return {
    subject: renderWithTokens(subjectTemplate, context),
    html: renderWithTokens(htmlTemplate, context),
    text: renderWithTokens(textTemplate, context),
  }
}

export async function POST(request: NextRequest) {
  try {
    await requireAdminAuth()
    const admin = await getAdminUser()
    const payload = await request.json()
    const id = typeof payload?.id === 'string' ? payload.id : ''
    if (!id) {
      return NextResponse.json({ error: 'Onboarding ID is required.' }, { status: 400 })
    }

    const records = await loadPartnerOnboardingRecords()
    const record = records.find((entry) => entry.id === id)

    if (!record) {
      return NextResponse.json({ error: 'Onboarding record not found.' }, { status: 404 })
    }

    if (!record.agreementAcceptedAt) {
      return NextResponse.json(
        { error: 'Agreement must be accepted before sending partner details.' },
        { status: 400 },
      )
    }

    const policies = await loadPolicies()
    const referralConfig = resolvePartnerReferralConfig(record, policies)
    const commissionPercent = referralConfig.commissionPercent

    const { code: promoCode, validUntilIso } = await ensurePromoCode(record, commissionPercent, referralConfig)

    const now = new Date()
    const validUntilDisplay = new Date(validUntilIso).toLocaleDateString('en-GB', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    })

    const { html, text, subject } = buildDetailsEmail({
      partner: record,
      promoCode,
      validUntil: validUntilDisplay,
      referralConfig,
      studioEmail: studioContactEmail,
    })

    const emailResult = await sendPartnerOnboardingEmail({
      to: record.email,
      subject,
      html,
      text,
    })

    const updatedRecord =
      (await updatePartnerOnboardingRecord(record.id, {
        promoCode,
        detailsEmailSentAt: emailResult.success ? now.toISOString() : record.detailsEmailSentAt ?? null,
        detailsEmailStatus: emailResult.success ? 'sent' : 'error',
        detailsEmailError: emailResult.success ? null : emailResult.error || 'Unable to send partner details email',
      })) || record

    await revalidatePath('/admin/partner-onboarding')
    await revalidatePath('/admin/referrals-tracking')

    await recordActivity({
      module: 'email',
      action: 'send',
      performedBy: admin?.username || 'owner',
      summary: `Sent referral details to ${updatedRecord.businessName}`,
      targetId: updatedRecord.id,
      targetType: 'partner_onboarding',
      details: {
        promoCode,
        emailStatus: emailResult,
      },
    })

    return NextResponse.json({
      success: emailResult.success,
      record: updatedRecord,
      promoCode,
      emailResult,
      error: emailResult.success ? null : emailResult.error || 'Unable to send partner details email',
    })
  } catch (error: any) {
    console.error('Error sending partner details email:', error)
    if (error instanceof Error && error.message === 'Unauthorized') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }
    return NextResponse.json(
      { error: error?.message || 'Failed to send partner details email.' },
      { status: 500 },
    )
  }
}


