import { NextRequest, NextResponse } from 'next/server'
import { readDataFilePreferRemote, writeDataFile } from '@/lib/data-utils'
import { normalizePromoCatalog, type PromoCode } from '@/lib/promo-utils'
import { loadPolicies } from '@/lib/policies-utils'
import {
  getFriendBookingDiscount,
  getAvailableReferrerRewardPercent,
  getReferralDefaultsFromPolicies,
  getReferrerBookingDiscount,
  resolveFriendDiscountSettings,
} from '@/lib/referral-utils'

export async function POST(request: NextRequest) {
  try {
    const raw = await readDataFilePreferRemote('promo-codes.json', {})
    const { catalog, changed } = normalizePromoCatalog(raw)

    if (changed) {
      await writeDataFile('promo-codes.json', catalog)
    }

    const body = await request.json()
    const { code, email, isFirstTimeClient, referralType } = body as {
      code?: string
      email?: string
      isFirstTimeClient?: boolean
      referralType?: 'friend' | 'salon' | null
    }

    if (!code) {
      return NextResponse.json({ valid: false, error: 'Promo code required' }, { status: 400 })
    }

    const promoCode = catalog.promoCodes.find((promo) => promo.code.toLowerCase() === code.toLowerCase())

    if (!promoCode || promoCode.active === false) {
      return NextResponse.json({
        valid: false,
        error: 'Invalid promo code',
        code: 'INVALID',
      }, { status: 404 })
    }

    const normalizedReferrerEmail = promoCode.referrerEmail?.toLowerCase() || null
    const requesterEmail = typeof email === 'string' ? email.toLowerCase() : null
    const isReferral = promoCode.isReferral === true
    const isSalonReferral = promoCode.isSalonReferral === true
    const isReferrer = Boolean(normalizedReferrerEmail && requesterEmail && normalizedReferrerEmail === requesterEmail)
    const allowsFirstTime = promoCode.allowFirstTimeClient ?? false

    // SECURITY: Check if this is a welcome discount code
    const isWelcomeDiscount = promoCode.autoGenerated === true && 
      (promoCode.description?.toLowerCase().includes('welcome discount') || 
       promoCode.description?.toLowerCase().includes('newsletter subscribers'))

    // SECURITY: If this is a welcome discount, check if email has already used one AND check 40-day validity
    if (isWelcomeDiscount && email) {
      const normalizedEmail = email.toLowerCase().trim()
      const welcomeDiscountData = await readDataFilePreferRemote<{ recipients: Array<{ email: string; receivedAt: string; promoCode?: string; usedAt?: string }> }>(
        'welcome-discount-recipients.json',
        { recipients: [] }
      )
      
      const existingRecipient = welcomeDiscountData.recipients.find(
        (recipient) => recipient.email.toLowerCase() === normalizedEmail
      )
      
      // If they've already used a welcome discount (not just received one), block them
      if (existingRecipient && existingRecipient.usedAt) {
        return NextResponse.json({
          valid: false,
          error: 'You have already used your welcome discount. Each email address can only use the welcome discount once.',
          code: 'WELCOME_DISCOUNT_ALREADY_USED',
        }, { status: 400 })
      }
      
      // Check if they received the code and if it's still within 40 days
      if (!existingRecipient || !existingRecipient.receivedAt) {
        return NextResponse.json({
          valid: false,
          error: 'This welcome discount code is only available to new newsletter subscribers. Please sign up via the popup on our homepage to receive your discount code.',
          code: 'WELCOME_DISCOUNT_NOT_RECEIVED',
        }, { status: 400 })
      }
      
      // Validate 40-day window from when they received the code
      const receivedDate = new Date(existingRecipient.receivedAt)
      if (isNaN(receivedDate.getTime())) {
        return NextResponse.json({
          valid: false,
          error: 'Invalid welcome discount record. Please contact support.',
          code: 'WELCOME_DISCOUNT_INVALID',
        }, { status: 400 })
      }
      
      const today = new Date()
      const daysSinceReceived = Math.floor((today.getTime() - receivedDate.getTime()) / (1000 * 60 * 60 * 24))
      
      if (daysSinceReceived > 40) {
        return NextResponse.json({
          valid: false,
          error: 'Your welcome discount code has expired. The code is valid for 40 days from when you joined The LashDiary community. Please book soon to take advantage of future discounts!',
          code: 'WELCOME_DISCOUNT_EXPIRED',
        }, { status: 400 })
      }
    }

    const parseDateOnly = (dateStr: string): Date | null => {
      if (!dateStr || typeof dateStr !== 'string') return null
      const parts = dateStr.split('-')
      if (parts.length === 3) {
        const year = parseInt(parts[0], 10)
        const month = parseInt(parts[1], 10) - 1
        const day = parseInt(parts[2], 10)
        if (!isNaN(year) && !isNaN(month) && !isNaN(day)) {
          const date = new Date(year, month, day)
          date.setHours(0, 0, 0, 0)
          return date
        }
      }
      const parsed = new Date(dateStr)
      parsed.setHours(0, 0, 0, 0)
      return isNaN(parsed.getTime()) ? null : parsed
    }

    const today = new Date()
    today.setHours(0, 0, 0, 0)

    if (promoCode.validFrom) {
      const starts = parseDateOnly(promoCode.validFrom)
      if (starts && starts > today) {
        return NextResponse.json({ valid: false, error: 'This promo code is not yet valid.' }, { status: 400 })
      }
    }

    if (promoCode.validUntil) {
      const ends = parseDateOnly(promoCode.validUntil)
      if (ends && ends < today && !(isReferral && !isSalonReferral && isReferrer)) {
        return NextResponse.json({ valid: false, error: 'This promo code has expired.' }, { status: 400 })
      }
    }

    if (promoCode.usageLimit && typeof promoCode.usedCount === 'number' && promoCode.usedCount >= promoCode.usageLimit) {
      return NextResponse.json({ valid: false, error: 'This promo code has reached its usage limit.' }, { status: 400 })
    }

    if (requesterEmail) {
      const usedByEmails = Array.isArray(promoCode.usedByEmails)
        ? promoCode.usedByEmails.map((e: string) => e.toLowerCase())
        : []
      if (usedByEmails.includes(requesterEmail)) {
        return NextResponse.json({
          valid: false,
          error: 'You have already used this promo code. Each promo code can only be used once per email address.',
          code: 'PROMO_ALREADY_USED',
        }, { status: 400 })
      }
    }

    if (isReferral && !isSalonReferral) {
      const friendUsesRemaining =
        typeof promoCode.friendUsesRemaining === 'number' ? promoCode.friendUsesRemaining : null
      const policies = await loadPolicies()
      const policyDefaults = getReferralDefaultsFromPolicies(policies.variables)
      const availableReferrerReward = getAvailableReferrerRewardPercent(promoCode, policyDefaults)

      if (isReferrer) {
        if (availableReferrerReward <= 0) {
          return NextResponse.json({
            valid: false,
            error: 'Your referral reward has already been used or is not yet unlocked.',
            code: 'REFERRAL_REFERRER_ONLY',
          }, { status: 400 })
        }
      } else {
        if (friendUsesRemaining !== null && friendUsesRemaining <= 0) {
          return NextResponse.json({
            valid: false,
          error: 'This referral code has reached its friend referral limit.',
            code: 'REFERRAL_FRIEND_LIMIT',
          }, { status: 400 })
        }
        if (isFirstTimeClient === true && allowsFirstTime === false) {
          return NextResponse.json({
            valid: false,
            error: 'This referral code cannot be used on a first visit.',
            code: 'REFERRAL_FIRST_TIME_BLOCKED',
          }, { status: 400 })
        }
      }
    } else if (isSalonReferral) {
      if (promoCode.salonUsageLimit != null && typeof promoCode.salonUsedCount === 'number' && promoCode.salonUsedCount >= promoCode.salonUsageLimit) {
        return NextResponse.json({
          valid: false,
          error: 'This salon referral code has reached its usage limit.',
          code: 'SALON_LIMIT_REACHED',
        }, { status: 400 })
      }
      if (referralType && referralType !== 'salon') {
        return NextResponse.json({
          valid: false,
          error: 'Please select “Referred by a salon / beautician / influencer” to use this code.',
          code: 'SALON_USE_REQUIRED',
        }, { status: 400 })
      }
    }

    if (!isReferral && !isSalonReferral && allowsFirstTime === false && isFirstTimeClient === true) {
      return NextResponse.json({
        valid: false,
        error: 'This promo code cannot be used by first-time clients. Please book your first appointment to become eligible.',
        code: 'CARD_FIRST_TIME_BLOCKED',
      }, { status: 400 })
    }

    let effectiveDiscountType = promoCode.discountType
    let effectiveDiscountValue = promoCode.discountValue

    let referralSettingsForResponse: ReturnType<typeof resolveFriendDiscountSettings> | undefined

    if (isReferral && !isSalonReferral) {
      const policies = await loadPolicies()
      const policyDefaults = getReferralDefaultsFromPolicies(policies.variables)
      referralSettingsForResponse = resolveFriendDiscountSettings(promoCode, policyDefaults)
      const isReferrerBooking = normalizedReferrerEmail === requesterEmail

      if (isReferrerBooking) {
        const referrerDiscount = getReferrerBookingDiscount(promoCode, policyDefaults)
        effectiveDiscountType = referrerDiscount.discountType
        effectiveDiscountValue = referrerDiscount.discountValue
      } else {
        const friendDiscount = getFriendBookingDiscount(promoCode, policyDefaults)
        effectiveDiscountType = friendDiscount.discountType
        effectiveDiscountValue = friendDiscount.discountValue
      }

      if (!isReferrerBooking && !referralSettingsForResponse.friendDiscountEnabled) {
        effectiveDiscountValue = 0
      }
    }

    const sanitized = {
      code: promoCode.code,
      description: promoCode.description || '',
      discountType: effectiveDiscountType,
      discountValue: effectiveDiscountValue,
      minPurchase: promoCode.minPurchase ?? 0,
      maxDiscount: promoCode.maxDiscount ?? null,
      isReferral,
      referrerEmail: normalizedReferrerEmail,
      referrerName: promoCode.referrerName ?? null,
      friendUsesRemaining: promoCode.friendUsesRemaining ?? null,
      friendReferralLimit: promoCode.friendReferralLimit ?? null,
      friendRedemptionCount: promoCode.friendRedemptionCount ?? 0,
      referrerRewardRedeemedCount: promoCode.referrerRewardRedeemedCount ?? 0,
      referralValidDays: promoCode.referralValidDays ?? null,
      referrerRewardAvailable:
        referralSettingsForResponse !== undefined
          ? getAvailableReferrerRewardPercent(promoCode) > 0
          : promoCode.referrerRewardAvailable ?? false,
      allowFirstTimeClient: allowsFirstTime,
      appliesToReferrer: isReferral ? normalizedReferrerEmail === requesterEmail : false,
      appliesToFriend: isReferral ? normalizedReferrerEmail !== requesterEmail : false,
      friendDiscountEnabled: referralSettingsForResponse?.friendDiscountEnabled,
      friendDiscountPercent: referralSettingsForResponse?.friendDiscountPercent,
      referrerRewardPercent: referralSettingsForResponse?.referrerRewardPercent,
      isSalonReferral,
      salonName: promoCode.salonName ?? null,
      salonEmail: promoCode.salonEmail ?? null,
      salonPartnerType: promoCode.salonPartnerType ?? 'salon',
      clientDiscountEnabled: promoCode.clientDiscountEnabled !== false,
      clientDiscountPercent: promoCode.clientDiscountPercent ?? null,
      clientDiscountAmount: promoCode.clientDiscountAmount ?? null,
      salonCommissionType: promoCode.salonCommissionType ?? 'percentage',
      salonCommissionPercent: promoCode.salonCommissionPercent ?? null,
      salonCommissionAmount: promoCode.salonCommissionAmount ?? null,
      salonUsageLimit: promoCode.salonUsageLimit ?? null,
      salonUsedCount: promoCode.salonUsedCount ?? 0,
    }

    return NextResponse.json({ valid: true, promoCode: sanitized })
  } catch (error) {
    console.error('Error validating promo code:', error)
    return NextResponse.json({ valid: false, error: 'Failed to validate promo code' }, { status: 500 })
  }
}
